### ISSUE TITLE
Details and information panels

### ISSUE THREAD

**Issue by djwesto** [folklabs/hernehill.org.uk#101]
We need a consistent styling to be applied to the typography and layout of the detail and info panels which appear in various spots:

![panel-details-group](https://f.cloud.github.com/assets/702685/1975722/10fd29f2-8381-11e3-86e9-bccf841defbd.png)

![panel-details-service-map](https://f.cloud.github.com/assets/702685/1975725/14d573a4-8381-11e3-9569-c7bac69146d3.png)

![panel-details-venue](https://f.cloud.github.com/assets/702685/1975734/2d011e92-8381-11e3-9d0f-0990935a9585.png)

This shouldn't be too tricky since they're all pretty similar.

**Comment by pmackay** [comment]
Looking a lot better after review on Friday and earlier work. Any remaining issues could be raised specifically.
