### ISSUE TITLE
Add a "What's hot?" panel list to Home page right hand column

### ISSUE THREAD

**Issue by djwesto** [folklabs/hernehill.org.uk#130]
Add a second panel under the Latest Forum Posts panel to display the latest 6 content additions to the site from Comments on News Articles, Groups, Events, Campaigns, Galleries, Services(?).

Each post should have the following fields exposed:
- Title
- User name (linked to profile page)
- Date / Time (perhaps displayed relative to present time)

**Comment by pmackay** [comment]
@GilesGibson the list is there and doesnt show the numbers, which seemed to be remaining sticking point. Can we close this?

**Comment by GilesGibson** [comment]
lets review how it works after a while.
