### ISSUE TITLE
Enhance content category taxonomies for Services, News, Groups etc

### ISSUE THREAD

**Issue by djwesto** [folklabs/hernehill.org.uk#149]
We need finalised category taxonomy listings added to this Google Drive doc

https://docs.google.com/spreadsheet/ccc?key=0AvwNdTyma3n1dENoTk5zbXRzUUFKcGM0LTloWENlS3c&usp=drivesdk#gid=0

**Comment by pmackay** [comment]
I've just tried adding (for the 1st time) the list of what I think are the set of Categories here:

http://dev-openlocal.pantheon.io/node/add/ol-news-article

However its a pretty long list, we probably need to reduce or review how they are displayed.

**Comment by djwesto** [comment]
@GilesGibson If you approve what we've done today on Service and Places Categories, we might be able to close this one...

**Comment by pmackay** [comment]
@djwesto annoyingly the doc seemed to crash and I had to rollback to an earlier one to restore. So it probably needs reassembling unless you have a copy locally?

**Comment by GilesGibson** [comment]
how will we sort the list of categories for services?

**Comment by pmackay** [comment]
Sorting can be alphabetic same as tags if needed.

Spreadsheet now updated so closing.
