### ISSUE TITLE
Create help pages for all the action button pane help links

### ISSUE THREAD

**Issue by pmackay** [folklabs/hernehill.org.uk#156]
@GilesGibson, do you have any thoughts on the style or format of the help pages for each content type?

**Comment by djwesto** [comment]
Have now started a help doc on Google Drive: https://docs.google.com/document/d/1guwt-VW1hGhgm1S11MkKNZ6Gzqo9GX3_JQ4fAl0xgjI/edit#

**Comment by GilesGibson** [comment]
We can encourage the testers to help suggest text and visuals for the help file.

**Comment by pmackay** [comment]
Closing as help links removed.
