### ISSUE TITLE
Discover - breadcrumb issue

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#193]
Not sure if this route is what is intended.

Click on discover.

Click on a gallery under the "galleries" column on the right hand side.

You then get the pictures in that gallery.

The breadcrumb at the top then just shows "home" as the only option, no way back to Discover. If galleries is a sub folder of Home I am assuming that we are not allowing people to go their directly, they have to go via the discover page. If so then it would be more consistent to return via the discover page.

**Comment by pmackay** [comment]
No longer relevant.
