### ISSUE TITLE
user account - incorect version history

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#214]
![image](https://f.cloud.github.com/assets/6060985/2114755/da3e0e1c-9042-11e3-883f-76739acf1813.png)r

I was in Forum posting. Clicked on my name as the person who posted a post. It took me to this menu above. This implies that there are items requiring moderation approval. However, it had already ben published so most of the info in the list was inaccurate.

**Comment by pmackay** [comment]
Is this now resolved with the current user profile tables and tabs for published/draft content?

**Comment by GilesGibson** [comment]
will check when I have created content again, current login has little or no content. Not sure what login name I used for the original issue. Too many sites to figure out logins and test users  aaarrrgh!
