### ISSUE TITLE
Services - filtering and tags

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#230]
New filter via tags looks good. Will need a "reset all" option for tags though. 

Aslo:

![image](https://f.cloud.github.com/assets/6060985/2152752/54115d06-941d-11e3-9415-f5a09b52782b.png)

The breadcrumb didn't work when I went backwards from a category filter back a level. I was hoping to be bale to get back to services but the breadcrumb will not let me do anything but back to Home.

**Comment by pmackay** [comment]
Have added a Reset filters link.

**Comment by GilesGibson** [comment]
thanks for this.
