### ISSUE TITLE
Fix news item styling

### ISSUE THREAD

**Issue by pmackay** [folklabs/hernehill.org.uk#236]
![screen shot 2014-03-28 at 09 53 06](https://cloud.githubusercontent.com/assets/115115/2548216/d7739b9c-b65e-11e3-91b4-8d31a989e790.png)

* comments info
* overlapping text
* overlapping author image and name
* changing format when no image present (just need a default image?)

**Comment by pmackay** [comment]
Need proposal for new layout to move this on.

**Comment by djwesto** [comment]
OK here's a comp showing a proposed layout for the front page news article listing. As we discussed the other day, we needed a version which includes an image and another which doesn't – you can see both in the same listing in this comp:

![screenshot 2015-01-23 12 30 38](https://cloud.githubusercontent.com/assets/702685/5874614/af512bae-a2fb-11e4-9581-b630e57538d8.png)

And here's a comp showing how each list item responsively narrows for mobile view until the text block flips down underneath the story's Featured Image:

![screenshot 2015-01-23 12 59 36](https://cloud.githubusercontent.com/assets/702685/5874992/bb066690-a2ff-11e4-9aa6-6ebc81c33767.png)

**Comment by pmackay** [comment]
Fixed on dev.
