### ISSUE TITLE
Redirect users to their login edit page to update their address details

### ISSUE THREAD

**Issue by pmackay** [folklabs/hernehill.org.uk#257]

**Comment by pmackay** [comment]
How about:

> Please go to your user profile and enter your street in "Address 1" and your postcode, just to help us show you really local, relevant information.

@GilesGibson @djwesto

**Comment by pmackay** [comment]
Have enabled this message to show when user logs in. I think a redirect is a bit intrusive.

**Comment by GilesGibson** [comment]
lets see how it works. We may need to come back to this to encourage people to be more detailed.
