### ISSUE TITLE
EU compliance buttons not displaying properly

### ISSUE THREAD

**Issue by pmackay** [folklabs/hernehill.org.uk#261]

**Comment by pmackay** [comment]
Look ok now on Chrome.

![screen shot 2015-01-15 at 20 39 56](https://cloud.githubusercontent.com/assets/115115/5766102/b8190e88-9cf6-11e4-9f50-e52123e099f5.png)

**Comment by djwesto** [comment]
Any chance we could take off the H2 tags from the text on that strip too?

**Comment by pmackay** [comment]
Done.
