### ISSUE TITLE
User login page - layout of "account" boxes

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#264]
Should the "I have a passord" box and the "I have an account" box look like that? Seems at odds with the normal layout.

![image](https://cloud.githubusercontent.com/assets/6060985/5250827/bd06413c-7987-11e4-8c4d-020d4b47d375.png)

**Comment by pmackay** [comment]
Styling of this page has now been improved somewhat. Those buttons work a *bit* more like tabs.
