### ISSUE TITLE
gallery post: characters and meta data

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#27]
test user - be useful to have some smart characters available for the description such as copyright symbol, Should we also have the picture owner in the meta data somewhere so Google can reference it?

**Comment by pmackay** [comment]
Currently albums are just storing plain text for credits. Closing as dont think special characters can easily be done.

**Comment by djwesto** [comment]
@GilesGibson, if a user wants to ensure their images are marked as copyrighted to them, then as @pmackay says, they can use the tool within their own computer to insert any characters they like. For instance, on the Mac, "©" is added by keying in Option+G. On a PC, you use the Character Map app to insert characters.

Would a more important point be for us to add in some parts of the Herne Hill general copyright agreement on the image upload page?

**Comment by GilesGibson** [comment]
Be good to have some guidance text next to the upload button area. Just making sure that people acknowledge copyright and credit any photographer etc etc.

Re: credits on pictures. There should be the field that is for credits - it was agreed at the meeting at the hub. If it could be bulk edited during the upload that would be great.
