### ISSUE TITLE
event creation - image location

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#273]
Can we give some explanation as to what/why/where the image is going to be used for. Some guidance as to appropriate size for instance and where the user will see it.

![image](https://cloud.githubusercontent.com/assets/6060985/5251662/529a2c66-798f-11e4-935c-d6442e2437d7.png)

**Comment by pmackay** [comment]
Text now updated on dev.

**Comment by GilesGibson** [comment]
OK for now. be nice to have a para after the first line though, text all compressed in.

**Comment by pmackay** [comment]
Lines now separated.
