### ISSUE TITLE
event creation - no valid venue

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#280]
I created an event but the venue I entered was a new one. It allowed me to enter it without validating it or asking if I wanted to add it to the venues collection.

Is this correct?

**Comment by pmackay** [comment]
I think "Select a venue" makes more sense. 

A create link can go in the help text.

**Comment by GilesGibson** [comment]
I agree that "select a venue" is better. "set a venue" is ambiguous, not quite sure what "set" means.

**Comment by pmackay** [comment]
Having fiddled with string naming for a bit, can I propose we solve this by updating the description?

>  If your event takes place in a physical space, please select it from our list of Herne Hill venues. Click "Add item" to show a list of all possible venues. Select a suitable venue and click "Submit". You can browse the list of available venues to see what is available.

**Comment by djwesto** [comment]
I can see the logic of this suggestion (assuming the "fiddling with string naming" really didn't work). But it's unlikely to be clear for a lot of users.

@GilesGibson does this suffice for you? Only way to tell is to test it I guess.

**Comment by pmackay** [comment]
I've got a fix to change the button text, which is on dev. Changing `No items have been added yet. Click "Add items" to launch the widget.` is much harder cos its dynamic, so going to leave that.

**Comment by pmackay** [comment]
@GilesGibson I think the text is about as good as I can customize it now. Please close if ok.

**Comment by GilesGibson** [comment]
lets leave it to the testers to see if they like it or not.
