### ISSUE TITLE
event viewing - repeats showing when there weren't any

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#282]
I created an event - when I view it via the repeat tab it is happy to show a screen showing a "repeat". 

![image](https://cloud.githubusercontent.com/assets/6060985/5252069/7544da1a-7992-11e4-8e01-c085d4152b93.png)

However, I didn't ask for a repeat on the event when I created it and what it shows doesn't look like a repeat. Bit confusing.

**Comment by pmackay** [comment]
I dont tihnk the module in D7 is likely to change this, given move to D8, etc.
