### ISSUE TITLE
community - viewing members - add new ones

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#298]
Would I want to add in new members?

![image](https://cloud.githubusercontent.com/assets/6060985/5253282/65d54f78-799d-11e4-8eaf-39db87eab47f.png)

Not sure if we need this but there may be a case for the group admin person(s) to be able to add in a new member.

**Comment by pmackay** [comment]
You can manage adding people and changing roles under the Group tab.

**Comment by GilesGibson** [comment]
OK, lets see how it works.
