### ISSUE TITLE
Accessing areas not allowed as not logged in - error messages

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#310]
I tried to add an event when I was not logged in. Got the standard error message page. Be good if we could explain that the user needs to be logged in first to be able to add content to the site and offer them a login option. 

![image](https://cloud.githubusercontent.com/assets/6060985/5266997/71df570c-7a45-11e4-9efd-eee847fab375.png)

**Comment by pmackay** [comment]
Fixed. Login form now shown.
