### ISSUE TITLE
Gallery preview option

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#324]
I went to preview the gallery created in the group coffee addicts. Looks rather strange - a collection of different typefaces etc. I assume this has yet to be themed?

![image](https://cloud.githubusercontent.com/assets/6060985/5268017/ba625bf2-7a4d-11e4-9f78-069f1f31b3f6.png)

**Comment by pmackay** [comment]
This has got a lot better with recent theming fixes.
