### ISSUE TITLE
Add content layout of page

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#332]
Logged on as standarduser - clicked on "add content" menu item on very top row of screen.

Layout of content add needs theming I think:

![image](https://cloud.githubusercontent.com/assets/6060985/5269026/c99e499c-7a56-11e4-99a5-95ca5535ff21.png)

**Comment by pmackay** [comment]
Improved http://dev-hernehill.gotpantheon.com/node/add

**Comment by GilesGibson** [comment]
Nice list. How is that maintained?

**Comment by pmackay** [comment]
Its a Drupal default page.
