### ISSUE TITLE
Button to add a picture to a gallery

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#348]
Should the user be able to add to the gallery via a simple button here?

![image](https://cloud.githubusercontent.com/assets/6060985/5271051/b52e43d8-7a68-11e4-8f8f-eb6a08095052.png)

**Comment by pmackay** [comment]
Photo album and gallery pages now have "add photos" buttons. And multi upload.

Although I wonder if the buttons should say "add photo album" as they are about adding a new album, not about adding photos to a current one.

**Comment by GilesGibson** [comment]
so if I wanted to add a picture to an existing gallery or album what text would be best?

**Comment by pmackay** [comment]
For that you just edit the current node.

**Comment by GilesGibson** [comment]
OK, but for the user, what text/button would they have to avoid the confusion between album/gallery and picture.

**Comment by pmackay** [comment]
Add photos adds a new album, Edit allows adding images to a current album.

**Comment by pmackay** [comment]
Some help text added to gallery pages for the button.

**Comment by GilesGibson** [comment]
Dev platform. Jst testing uploading bulk images. Got this message after uploading 40 pictures:

![image](https://cloud.githubusercontent.com/assets/6060985/5778518/cba230e0-9d93-11e4-8ee3-460946bb6c5a.png)


Why is the name being changed? Whose security reasons? Does GCHQ know about this or was it them who did it? I think we should be told....

**Comment by pmackay** [comment]
What was the original name of the file?

**Comment by GilesGibson** [comment]
It was the bulk upload of 40 or so files. Does this error refer to one file?

**Comment by pmackay** [comment]
It looks like it is just mentioning one filename that was changed.

**Comment by GilesGibson** [comment]
Hmm, could be. It may be the image of the bookshop was a problem. No idea how to track down the file name that caused the offence though. Would a duplicate on the site cause this?

**Comment by pmackay** [comment]
Can we close this related to the original button issue?

**Comment by GilesGibson** [comment]
OK, but if the latest error occurs again we will open a new one.
