### ISSUE TITLE
News item does not show comments

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#356]
I created the news item logged on as "giles", added two comments. The logged on as standarduser and could not see the comments.

![image](https://cloud.githubusercontent.com/assets/6060985/5271930/2752a218-7a70-11e4-82e0-7c2e0c7f3283.png)

**Comment by pmackay** [comment]
@GilesGibson could you please confirm if this is still an issue?

**Comment by GilesGibson** [comment]
on dev or live?

**Comment by pmackay** [comment]
Always dev currently

**Comment by GilesGibson** [comment]
will test again and create new issue if necessary
