### ISSUE TITLE
How does a user create a service listing?

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#361]
A logged in user needs to be able to submit their new service listing for moderation and acceptance. At the moment this process is convoluted, they email in, we send them a guide, they create a login, send that back to us, we create a blank listing, they edit it. 

As per previous discussions we need to streamline this. They can submit a service listing entry for publishing and await moderation/acceptance, we just publish it or not. Ideally they need to get some sort of words/guidance before they spend time writing it all up only then to be told that we don't accept listings for businesses in far away places.

**Comment by pmackay** [comment]
OK for now the Issue form has been improved with some prompts and specific items under "Type". I'd like to go with this for now as a fancier form that auto-populates a Service or Group is quite a bit more complex.

http://dev-hernehill.gotpantheon.com/node/add/ol-issue

**Comment by GilesGibson** [comment]
It is not too user friendly at the moment, I am confused about some of the terminology used so probably would be new users.

The descriptions at the top could do with editing losightly:

![image](https://cloud.githubusercontent.com/assets/6060985/5904179/91ef2234-a57e-11e4-80cf-41e5d2951346.png)


Could we have "add new business listing".
"add new group"
"report a website problem"

Not sure if we then need to duplicate with "support request".

**Comment by pmackay** [comment]
fixed on dev.
