### ISSUE TITLE
News item - does not appear for moderation when edited

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#369]
I created a news item as user "standarduser".
Logged on as Giles, changed to publish.
logged on as standarduser and edited the news item. It said that it was then in draft.
logged back in as Giles, could not see the news item in the workbench listing of items awaiting moderation/changes etc. Edited news item not showing up in news, which is correct as it should be waiting for moderation after the edits were done.

**Comment by pmackay** [comment]
@GilesGibson can this be closed?

**Comment by GilesGibson** [comment]
assuming it is fixed then yes.
