### ISSUE TITLE
Login screen - layout changes

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#373]
I have used the login screen for a good few times now and made numerous mistakes. I think if we can we need to look at how this is laid out, how it flows.

![image](https://cloud.githubusercontent.com/assets/6060985/5282632/01fc8494-7b00-11e4-95e4-3e100b95264a.png)

Basically if we can make the most common flow to be the easiest one to do, by hitting return, or minimal mouse movements then that would be better.

Relocate the "request new password" away from the Login button, easy to click on the wrong one if in a hurry.

If the user hits enter after each entry they should be moved to the next live entry point.

I find the size of the box round the input text means it is hard to read what you have entered when in poor light conditions. can it be larger?

For my poorly trained eye there seems to be a wide mix of typefaces and font sizes on the screen, large boxes at the top, slim data entry boxes and different prompting text.

**Comment by GilesGibson** [comment]
OK, looks much better, thanks.

Currently though when you hit enter after your email address it just thinks you have finished the entire page and so creates an error as there is no password. Be great to have a simple flow that has the minimal keystrokes to do the thing that is most popular i.e. email address, enter, password, enter and you are in.
I have added it to the backlog.

**Comment by pmackay** [comment]
If you press Tab you can jump between fields which is pretty standard.
