### ISSUE TITLE
Event creation - need explanatory text

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#379]
These fields need some explanatory text added to the right hand side.

Explain what is the purpose of Groups audience? why would you use it and what are the repercussions?

What is the meaning of groups content visibility? Explain the differences in visibility.

![image](https://cloud.githubusercontent.com/assets/6060985/5284171/689432c4-7b0a-11e4-912d-9661ecd8e079.png)

**Comment by pmackay** [comment]
How about these:

> If this event is related to a community group, select the group so the event appears on the group page.

and 

> By default events are public and visible to everyone. Change this setting if you wish to make the event visible only to people in the group.

**Comment by GilesGibson** [comment]
OK
