### ISSUE TITLE
publishing permissions for group members

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#386]
I think we need to revisit the issue about how group members can publish material. At the moment anyone can add themselves to a group and then post anything in that group, news, events etc. A spammers paradise. 

I know that having a complete sub-set of security with a group admin team moderating content is tough but can we look at some sort of grading system for members of a group. Maybe a simple way that the group admin people can allow a group member to be allowed to post an event or news item? A sub category or sub-level of permissions between a plain user and the group admin team.

**Comment by pmackay** [comment]
@GilesGibson would be sufficient if groups admins approve members?

**Comment by GilesGibson** [comment]
Yip, lets see how that works.

**Comment by pmackay** [comment]
I think on another issue I noted that groups now require approval for people to join. Can we close this?

**Comment by GilesGibson** [comment]
OK
