### ISSUE TITLE
Trader contact information layout

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#393]
Quick bit of feedback.

The layout of fhe trader info down the right hand side of the page.

![image](https://cloud.githubusercontent.com/assets/6060985/5331216/c3ad3296-7e16-11e4-9ae8-ca381c3029f2.png)

Suggestions:

Where is says "Contact person via email" does this mean "contact trader via email?" Maybe worth changing.

Can we have the twitter symbol next to the trader twitter handle? Then if people click on it they can immediately follow the trader.

Are we having facebook entry (and the facebook symbol)?

**Comment by pmackay** [comment]
Twitter icon not easy to add. FB now supported.
