### ISSUE TITLE
Contextual help wanted for Community page

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#399]
Feedback from various early testers. The Community page needs contextual help added to explain what the page is about.

![image](https://cloud.githubusercontent.com/assets/6060985/5331360/3a8f5610-7e20-11e4-9d74-a0a4419cd3c1.png)

**Comment by pmackay** [comment]
Done on dev.

**Comment by GilesGibson** [comment]
TA, looks good. Lets see what the real world thinks
