### ISSUE TITLE
Define the footer design

### ISSUE THREAD

**Issue by pmackay** [folklabs/hernehill.org.uk#40]

**Comment by pmackay** [comment]
@GilesGibson to provide logo or close issue, if footer is ok.

**Comment by GilesGibson** [comment]
Could the name "original thinking" just have an email link? info@originaltg.com?

Thanks.

Giles

**Comment by pmackay** [comment]
Updated on live.

**Comment by djwesto** [comment]
@GilesGibson... Would you like us to design a logo and website for Original Thinking? :grinning: 

I'm joking of course. One day...

Anyway, I'm going to add a new issue to backlog to get this footer lookging better in future versions.

**Comment by GilesGibson** [comment]
Got a logo. Got halfway through a website but got distracted. Feel free to.
