### ISSUE TITLE
Suggested addition to home page - more news items tab

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#401]
Should we have a "more news items" button or similar at the end of the news items on the front page? It would take users to the main news page. I am a bit worried that people may only think that there is only three items of news ever.

**Comment by pmackay** [comment]
"More news" link now present on dev, closing. Not sure about best option for other ideas mentioned here, should reevaluate w.r.t. other feedback.

**Comment by djwesto** [comment]
I think that (if we're temporarily abandoning the idea of the front page being a stream of all new content) then it **would** make sense if we make it a list of all the Featured News articles in order of most-recent first with a highlighted story right at the top.
