### ISSUE TITLE
Fix front page news item listing styles to be responsive

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#402]
I edited a news item that had some blank lines in early on. On the front page all this formatting is lost and the text all put on one continuous line. Is this correct?  Could cause problems.

any chance of the "more" being a bit more visible - colour? LIne below? 

Should the author appear next to the date?

![image](https://cloud.githubusercontent.com/assets/6060985/5332665/cf4cd418-7e56-11e4-8b42-3670b0e401d5.png)

**Comment by pmackay** [comment]
New lines are preserved now, paragraphs converted to newlines (`<br>` tags) which shows a return but no extra space. More link changed. Other formatting still removed as it is a teaser. General style of news teasers improved.

**Comment by GilesGibson** [comment]
Could we get the "comments" icon to be on the same bottom line as author and date?

![image](https://cloud.githubusercontent.com/assets/6060985/5904989/913d8cee-a584-11e4-8ab9-dcabc72ad1a7.png)


Brockwell Lido mid-winter swim news item looks a bit strange, as there is no text. Could there be a bit of theming improvements done here?

**Comment by pmackay** [comment]
What site are you viewing this on?

**Comment by GilesGibson** [comment]
www.hernehill.org.uk

**Comment by djwesto** [comment]
Can you check http://dev-hernehill.gotpantheon.com/ instead?

Paul's not pushing all dev changes to live all the time now.

**Comment by GilesGibson** [comment]
OK, I am really confused now. I had thought that you wanted all testing done on hernehill.org.uk. That is the address I have sent out to the beta testers too, as instructed. Could you elaborate on what sites are now being used and what ones we can ignore. Ta.

**Comment by pmackay** [comment]
The live site is a recent snapshot of functionality that other testers
could use to give feedback. However if we are fixing stuff on the issue
queue since we setup the live site, it will only be pushed to dev. So if
you want to test updated issues on dev thats great. But I wouldnt ask other
testers to look at dev.

**Comment by GilesGibson** [comment]
OK, can I try and clarify this.

What is www.hernehill.org.uk? Is that the "live" site?

What is the http://live-hernehill.gotpantheon.com/ now?

What is http://dev-hernehill.gotpantheon.com/?

I have been reporting back from www.hernehill.org.uk as requested. Should I still do this or use one of the other older sites?

When are we keeping www.hernehill.org.uk updated?

Ta

**Comment by pmackay** [comment]
www.hernehill.org.uk and http://live-hernehill.gotpantheon.com/ are
pointing at the same site.

http://dev-hernehill.gotpantheon.com/ is the dev site where we push changes
as we're developing things.

http://test-hernehill.gotpantheon.com
<http://dev-hernehill.gotpantheon.com/> is where we would combine latest
dev changes with content from the live site, but we're not using it much in
our current workflow.

Reporting issues raised by others from the live site is great. Keep going :)

We need to agree a process for updating the live site, but its too much
work to update every time we fix one issue. We can start a release process
perhaps.

**Comment by djwesto** [comment]
For what it's worth, my understanding of how this process works is that Paul and I push fixes to dev for you to check, Giles.

But then, once you've approved those solutions and are happy with the way they're working, they then get pushed to the live beta testing environment (where your team can check it) at a less regular interval.

Does that make sense?

**Comment by GilesGibson** [comment]
OK, that helps. So do you want me to go back to testing dev again?

**Comment by pmackay** [comment]
Any updates now posted on issues will be on dev. Its great if you can or want to test them and confirm its ok. Otherwise wait and we agree a dev -> live process.

**Comment by djwesto** [comment]
Yep, please review the actual topic of this issue (the formatting of the News article listing) on dev- and let us know if you're happy with it now.

**Comment by GilesGibson** [comment]
OK for now. Will open again if the layout gets messed up for some reason.
