### ISSUE TITLE
News article layout if no image is provided

### ISSUE THREAD

**Issue by pmackay** [folklabs/hernehill.org.uk#410]
![screen shot 2014-12-09 at 11 37 48](https://cloud.githubusercontent.com/assets/115115/5356751/f0de90c0-7f97-11e4-9338-39d62d382d6d.png)
@GilesGibson should this layout be tweaked if some articles dont have images? How likely is that? Its currently based on the idea that there is a top featured image, then the author info, then the text. Should author info go under text? 

This will also be true for imported content, as none of them will have a featured image.

**Comment by djwesto** [comment]
There are a few points in this discussion which need to be addressed:
* Great if authors are going to be encouraged to add more pics but, inevitably, there'll be plenty of occasions when there isn't an image to go with a story.
* If authors uploading PDFs is a big problem, we could catch each PDF and convert the front page of each PDF into that node's Featured Image using **PDF to Imagefield** module: https://www.drupal.org/project/pdf_to_imagefield. I can open a new issue if @pmackay thinks it's a good idea?
* We could even then allow PDFs to be displayed on the node page itself using something like the PDF module: https://www.drupal.org/project/pdf but @pmackay may think that's going too far. But if it's a good idea, I'll open a new issue.
* @GilesGibson I don't quite get the point you're making about the layout but take a look at the visual below which I've mocked up. I'm proposing this as the new layout for news pages without a Featured Image:

![screenshot 2015-01-13 10 51 30](https://cloud.githubusercontent.com/assets/702685/5719642/2e2d9800-9b12-11e4-9b49-cbeac2302017.png)

NB. @pmackay, I think this layout for the metadata in the sidebar is the same as for news pages with featured images.

**Comment by GilesGibson** [comment]
The issue about the layout was just about the news item not allowing the text to flow to the left if there was no picture. It makes the page disjointed and not visually appealing. 

If there was a reliable way of allowing pdf's to be displayed then that would help. So many items in events for instance are just pdf's of the poster and people want to upload them. News items often need a pdf as well. At the moment it is a pain having to convert the pdf to a jpeg and then having a low resolution image displayed. Not great.

@djwesto I am happy with the layout above for news items that have no picture.

**Comment by djwesto** [comment]
Fantastic, thanks @GilesGibson – we'll go ahead and build that then and see if we can include the PDF module option as well. @pmackay Let's discuss this later today.

**Comment by djwesto** [comment]
Think this can now be closed, @pmackay?
