### ISSUE TITLE
News item images overflow on home page

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#413]
The news item carousel is allowing images to overflow:

allows images inserted into the main body of text t
![image](https://cloud.githubusercontent.com/assets/6060985/5363370/71c85960-7fd3-11e4-874c-f4c8e515baec.png)

**Comment by djwesto** [comment]
Google doc containing a new table of Image Styles is here: https://docs.google.com/document/d/1qCmOq_SI5JxjXodi48By3-XqvTkaBej5XUVDZ-igE0s/edit

@pmackay has agreed to take this on and convert all the existing image styles.

**Comment by pmackay** [comment]
@djwesto do you have a comp for the highlight box? What should title look like overlaid on the image? What colour and transparency value for background?

**Comment by djwesto** [comment]
Here's a comp for the home page highlight panel with typography and transparent backgrounds behind the text.

Any objections to this approach, @GilesGibson ?

Also, @pmackay were you proposing that you'd set these styles up and that I'd then finish it off or something? I wouldn't mind knowing what you can do for headlines that are too long to fit into – say – 60 characters? Would you truncate them with a ". . ." after and a "More >" link or something else?

![screenshot 2015-01-15 19 17 46](https://cloud.githubusercontent.com/assets/702685/5764592/35a9bda4-9ceb-11e4-8a3b-95aa415fc55e.png)

Please also note the "N of N" indicataor has shifted to top-left to avoid the heading text overlapping it.

**Comment by GilesGibson** [comment]
Lets see how it works. Nice idea.

**Comment by djwesto** [comment]
Please check the front page at http://dev-hernehill.gotpantheon.com for the new styling which is implemented:

![screenshot 2015-01-16 13 38 28](https://cloud.githubusercontent.com/assets/702685/5776855/0ada68e0-9d85-11e4-8adf-127e54a201d1.png)

I'm closing but please alert us, @GilesGibson if you have any issues with this?
