### ISSUE TITLE
URL path for Groups still includes /campaigns/

### ISSUE THREAD

**Issue by djwesto** [folklabs/hernehill.org.uk#414]
Not sure which of you two to assign this to, so am going to assign to @pmackay... I was just looking at the Groups landing pages to see how they are laid out when I noticed in the Edit Group node edit page that the automatically-generated URL includes /campaigns/ in the path, rather than /groups/ or /community-group/ or something similar.

What should it be? I am still really confused by this use of "Services" and "Community" when what we're actually talking about are "Local traders" or "Local businesses" and "Groups":

![screenshot 2014-12-16 16 35 51](https://cloud.githubusercontent.com/assets/702685/5457347/cd97afa2-8541-11e4-8d7a-9c1594a864a7.png)

Can we review on Thurs?

**Comment by pmackay** [comment]
Have got migrate process to resolve this.

**Comment by pmackay** [comment]
Think this is resolved but have raised #483 which has appeared.
