### ISSUE TITLE
Theming for tables to be improved

### ISSUE THREAD

**Issue by djwesto** [folklabs/hernehill.org.uk#420]
Many tables need proper styling and theming as they currently don't look right. This example from the HH Shop Local Card landing page is a great example (http://dev-hernehill.gotpantheon.com/content/herne-hill-card):

![image](https://cloud.githubusercontent.com/assets/702685/5473856/83e7edf4-8604-11e4-98f9-06d16b7835d4.png)

**Comment by djwesto** [comment]
OK here's a new comp showing how I think tables should look. I'd love it if we could also add some column alignment classes in there using *col* and *colgroup* elements but I'm assuming that's probably going to be a pig to do:

![screenshot 2015-01-14 17 24 51](https://cloud.githubusercontent.com/assets/702685/5743731/0a774422-9c13-11e4-9bd0-9e9019d6ab70.png)

In view of what Giles has been asking, this comp relates to styling only – not functions of the table which probably need to be reviewed.

I'll try to make a start on this once my local dev environment is working again.

**Comment by djwesto** [comment]
@GilesGibson and @pmackay Please check pages like http://dev-hernehill.gotpantheon.com/user for neater table styles now implemented. Alert me if you see any problems on other tables but otherwise this can be closed for now.

**Comment by pmackay** [comment]
Those tables look so good I want to eat my dinner off them.

[](http://i.giphy.com/2aFRDAaACkSXu.gif)

**Comment by GilesGibson** [comment]
OK, if there is nothing in the cointent then the user sees this (ignore the masquerade bt)

![image](https://cloud.githubusercontent.com/assets/6060985/5766728/a23aebc2-9cfb-11e4-8c26-6a994c439896.png)


Could we at least show the table headings and then blank underneath?

**Comment by pmackay** [comment]
Would a simple message saying "No content created so far" or similar be OK?

**Comment by GilesGibson** [comment]
Fine, as long as we respond to the user request with information - just delivering a blank page is not great, user not sure if system broken or what?

**Comment by GilesGibson** [comment]
I will need to create a bunch of content first and then go and look at it. Cannot see other peoples profile page....

**Comment by djwesto** [comment]
Could this go in a new issue (perhaps a generic one about alert notifications for empty content holders) so that I can close this issue?

**Comment by djwesto** [comment]
How's about this for the wording of the notification of "No content here"?

> Giles Gibson has not created any content yet. To make some new content, visit the [Add Content](/node/add) page and choose what you'd like to create.

We're hoping we can tokenise this so the user name will be related to the page you're looking at.

**Comment by GilesGibson** [comment]
Happy with that. we just need to approach empty results in the same way as a printed manual has "this page intentionally left blank" i.e. tell the user that it is blank and why.

**Comment by pmackay** [comment]
OK message added.

**Comment by GilesGibson** [comment]
great.
