### ISSUE TITLE
Featured image selector needs media library widget type

### ISSUE THREAD

**Issue by djwesto** [folklabs/hernehill.org.uk#425]
Currently featured images on most content types offer the standard File Upload field as a means of adding a Featured Image. But we should look at switching this to the Media Library widget which would allow us to add photos which have been uploaded to the site by users.

It would be interesting to look at how to enhance the Media Library widget to allow the file structure or other tools to be used to ensure it's not too overwhelming. @GilesGibson mentioned the need for images to be searchable or better organised.

**Comment by pmackay** [comment]
Sticking with image widget.
