### ISSUE TITLE
Check permissions – a user can add "My follow links" to another users' profile

### ISSUE THREAD

**Issue by djwesto** [folklabs/hernehill.org.uk#428]
Logged in as: jeanb
Dev instance: http://dev-hernehill.gotpantheon.com 
URL where I first noticed the issue: http://dev-hernehill.gotpantheon.com/user/1/follow

1. As a test, I tried to add a "Follow Link" to the user profile for "admin" while I was masquerading as "jeanb"
2. I added the HH Facebook page to the Facebook field and submitted it.
3. Lo and behold, the system accepted my profile link.

Is this simply a permissions issue we can easily fix or something which means it might be worth hiding My Follow Links altogether for now? Since no users can currently see another user's "Profile Page" anyway, where does this set of social links appear?

**Screenshot**
![screenshot 2015-01-14 12 27 01](https://cloud.githubusercontent.com/assets/702685/5738818/cbbc5670-9be8-11e4-9598-af88af29c11e.png)

CHECKLIST:
- [x] Duplicate issues check complete
- [x] Labelled correctly
- [x] Assigned to team member
- [x] Milestone added
- [ ] Links to existing issues or Trello cards added

**Comment by pmackay** [comment]
This comes from https://www.drupal.org/project/follow, but do we need that module? I think we should remove it personally. Not quite sure how it got there.

**Comment by djwesto** [comment]
I don't know how it got there either. It's not necessary right now since we're not even actually allowing any other users to view one another's user profiles so the Follow links won't appear anywhere.

Great to be able to remove a module we don't need! But before you do (just to check) it's not what's driving the Twitter and Facebook links which appear at the top of every page is it?

**Comment by pmackay** [comment]
No, they are hardcoded.
