### ISSUE TITLE
Examine why user avatars not appearing anywhere on site

### ISSUE THREAD

**Issue by djwesto** [folklabs/hernehill.org.uk#429]
We have a bit of a problem with Avatars which I'd noticed when using Admin's account but have also realised is a problem with the account I just set up for myself.

Logged in as: chriswells
Dev instance: dev- Pantheon
URL: http://dev-hernehill.gotpantheon.com/user/8785/edit

* I set up a new user (chriswells)
* I uploaded a photo (the size limit is a min 300 x 200 pixels which is perhaps a tad large for avatars)
* I noticed I wasn't given the option to crop my image (see screenshot below) which meant it got cropped badly. This probably needs to be changed.

![screenshot 2015-01-14 13 51 54](https://cloud.githubusercontent.com/assets/702685/5739733/8811b274-9bf4-11e4-9108-a5e476abdc56.png)

* This is similar to the issue we are seeing with the Admin account not having an avatar appearing anywhere – is this a Panopoly issue or what?
* As part of this issue we also need to add a default user avatar image for when someone hasn't uploaded one – this appears in the backend interface but not on the front end. Here's the default for Admin's account:

![screenshot 2015-01-14 13 39 47](https://cloud.githubusercontent.com/assets/702685/5739616/70933ff6-9bf3-11e4-890a-d6b884e4aaf3.png)

**NEXT STEPS**
* We need to examine why this is happening – I recall at one stage a while back there were actually two User Avatar images appearing on pages: one was the native Drupal avatar and the other was Panopolies.
* I remember a conversation between Paul and I where he decided to remove or hide the native avatar in favour of the Panopoly one.
* Is this the reason for it now not appearing or is something else removing the avatars?

**CHECKLIST**
- [x] Duplicate issues check complete
- [x] Labelled correctly
- [x] Assigned to team member
- [x] Milestone added
- [ ] Links to existing issues or Trello cards added

**Comment by pmackay** [comment]
Fixed, see http://dev-hernehill.gotpantheon.com/users/admin.

**Comment by djwesto** [comment]
You're right. It seems to be fixed. Nice one! I even checked on article pages and they now feature user avatars too. Happy to close.
