### ISSUE TITLE
Twitter feed is shown on homepage left column

### ISSUE THREAD

**Issue by pmackay** [folklabs/hernehill.org.uk#430]

**Comment by pmackay** [comment]
@GilesGibson to provide twitter account info.

**Comment by pmackay** [comment]
Done.

**Comment by GilesGibson** [comment]
Looks great.What I used to do was scrape any reference to "herne hill". Captures more tweets that way. Any chance?

**Comment by pmackay** [comment]
Not really, thats a totally different query. This integrates directly with
your account. And scraping any tweets from a search wasnt mentioned before.
Would favour going with this for now.

**Comment by GilesGibson** [comment]
OK for now, can we move this to the backlog/wishlist?

**Comment by djwesto** [comment]
Hi @GilesGibson. I see your point about showing a search result in the Twitter feed but it isn't possible right now. However, there is a module which is still in development which could do this: https://www.drupal.org/project/twitter_search

Once it's out of dev, we could look at installing it but for now this needs to move to WishList.

**Comment by GilesGibson** [comment]
Great, we used to also get the tweets to do with Herne Hill, a suburb of Perth, it was great fun!
