### ISSUE TITLE
Unable to create new login

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#431]
Live site. test users have tried to create their login, they never receive their activation/authentication email.

**Comment by pmackay** [comment]
Do you happen to know if they've checked spam folders?

**Comment by djwesto** [comment]
As mentioned yesterday, the welcome message (which you should write some nicer text for, @GilesGibson by the way) is "clipped" when it is being viewed in a Gmail account.

![screenshot 2015-01-15 19 57 19](https://cloud.githubusercontent.com/assets/702685/5765344/bb5cacb8-9cf0-11e4-860a-43148f5530a5.png)

Also worth noting is that when I just registered a new user on live- Pantheon (chrisdwells) I received the email practically instantaneously *but* it got diverted to my spam folder.

Please could you ask all test users to check their spam folders (I assume they're all aware of what one is?) for an email titled:

> "Account details for [their chosen user name here] at Herne Hill"

**Comment by pmackay** [comment]
The site is not on a proper domain AND its got my mail in settings, so it
really looks like spam. This would be much improved if/when we change site
email to something@hernehill.org.uk and have the right domain.

**Comment by GilesGibson** [comment]
Yup, nothing there.

**Comment by djwesto** [comment]
Precisely what sort of mail system are they using?
* Is it their own mail server?
* Gmail
* Yahoo?
* Some sort of corporate mail server or school / local or central gov mail server with a paranoid firewall?

**Comment by GilesGibson** [comment]
It was Jan, as per the email I forwarded to you.Yan <yan.hawkins@btinternet.com>

**Comment by GilesGibson** [comment]
I have just had to redo my password on dev system. Authentication email went straight to spam. Happy to do some welcome text, where?

**Comment by pmackay** [comment]
Create or edit a doc on Drive?

**Comment by GilesGibson** [comment]
happy to edit a doc on drive

**Comment by GilesGibson** [comment]
dealt with via #433
