### ISSUE TITLE
New user creation - no indication of progress

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#433]
Dev platform.

I have just tried creating a new user - standarduser on the dev platform. Filled in the details etc and clicked on "create account" . It then went straight to the main home page of the web site. It took a while before I could see that there was a message across the top saying that an email had been sent. All a bit confusing.

Any chance we could leave the user on the create a user page, have the message come up there or ideally on its own page, nice and clear (ideally with text asking them to check their spam folder etc, then a button to click to go to the home page.

**Comment by pmackay** [comment]
Any chance you could get a screenshot of the message on the homepage and
why its not clear?

**Comment by GilesGibson** [comment]
![image](https://cloud.githubusercontent.com/assets/6060985/5767240/65b1da4a-9cff-11e4-984d-24af6acecbd3.png)

The banner line is there but I have to admit that I missed it for a while. I was expecting to be told within the login system what happened next, not being ut on to the main system and then having a message embedded it the screen.

**Comment by pmackay** [comment]
Please suggest what text/message you would user to see - we can have it
redirect to a custom page.

**Comment by GilesGibson** [comment]
Is this not the page where we save a whole load of support hassle by asking people to check their spam folder etc? When it doesn't get through on the system at the moment we get endless queries from users who cannot login. If we can pre-empt this by doing some nice helpful text - and a funny graphic @djwesto .. it would be great.

**Comment by djwesto** [comment]
I think, looking at that screenshot, one problem is that because our site's colour scheme features a lot of green, the success message gets quite lost. I'll try the following:

* Increase the size of text in all notifications
* Increase spacing above and below them to set them further apart from normal site content
* Increase colour contrast between notifications and the normal site content
* Perhaps introduce stronger graphics to draw more attention to them

@pmackay, is there a standard way this is currently handled (so all actions wind up back on the homepage after they complete) and are you thinking we'd introduce a global change so all actions wind up on a sort of *notification page* where you'd just see the notification on its own? How are you going to do the redirect for this one?

**Comment by pmackay** [comment]
@djwesto user registration can be redirected to a custom page (default is homepage). Other notifications would appear where they are generated. 

Who is writing the copy for this?

**Comment by djwesto** [comment]
@GilesGibson should kick off the writing of the help text he wants users to see and I will sense-check and edit.

**Comment by GilesGibson** [comment]
@djwesto "sense check!",  are you implying something? You may be correct but I am sure there is a better turn of phrase you could use, on the other hand in this particular case it is accurate.

Do we have a doc or something where we are collating all the help texts we are using?

**Comment by GilesGibson** [comment]
OK, I have done a draft on google drive - saved in the folder that I think is the correct one. 
https://docs.google.com/a/originaltg.com/document/d/1jRfPXfm3i-IEAhQaEE62Oqboj_S2OTiul_PNU_KzOok/edit?usp=sharing

**Comment by djwesto** [comment]
Hi @GilesGibson, do you happen to know this Herne Hill-based photographer on Flickr? https://www.flickr.com/photos/edek/

Some really stunning photos in there – well worth trying to contact him about using them across the site.

**Comment by djwesto** [comment]
Hi @GilesGibson please can you check the GDrive doc again to see what I've done to it? I've basically tightened up the language and formatting and added in the content you requested: https://docs.google.com/document/d/1jRfPXfm3i-IEAhQaEE62Oqboj_S2OTiul_PNU_KzOok/edit#

If you approve it, I can build a page with the content and get Paul to set it as the result page after registration

**Comment by GilesGibson** [comment]
Great, go make it so.

**Comment by GilesGibson** [comment]
Have emailed Erek about the pictures. To be honest there are also loads of local photographers who we could also tap in to. Good idea.
