### ISSUE TITLE
Tag filters on services listing - not alphabetical

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#435]
The tags for the filters on the servcies listings are a bit juimbled, no idea how you would find what you wanted.

![image](https://cloud.githubusercontent.com/assets/6060985/5767813/3252af68-9d03-11e4-8cf4-650dd3b4171d.png)

If we get more tags is there a merit of having a text search or predictive dropdown?

**Comment by pmackay** [comment]
When proper categories are in place, they should filter the tags a lot. Lets see how it works then. Also actually doing fancier UX things with this will take a lot of time.

**Comment by GilesGibson** [comment]
but will the tag list be sorted according to usual methods i.e. alphabetical?

**Comment by pmackay** [comment]
Currently it is sorted by number of items with that tag (number in brackets). That's quite typical and we'd recommend it. It is possible to sort by name though, please confirm preference?

**Comment by GilesGibson** [comment]
from the users point of view I would imagine that they were after a specific area i.e. yoga, or baby. I am not sure that their need to find something would be influenced by knowing that there were more builders in the listings than say yoga teachers. There may be some merit in listing via popularity of tag but not sure of the merits - am I missing something?

**Comment by pmackay** [comment]
Fixed on HH and OL.
