### ISSUE TITLE
Add spacing & strengthen line between bulk-uploaded image list

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#437]
Dev site. Uploaded 40 images to a gallery. It lists them all:

![image](https://cloud.githubusercontent.com/assets/6060985/5778564/280db0a2-9d94-11e4-9cf0-e49576503dcd.png)

hard to tell if the title is for the one above or below, needs a line or separator of some sort between each image.

**Comment by pmackay** [comment]
Added stronger divider.

**Comment by GilesGibson** [comment]
Ta
