### ISSUE TITLE
Album display - too long and not very pretty

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#439]
Dev site. Uploaded 40 images to a gallery. Went to view it - huge long parade of images down the page. Hard to see what is what and whilst great to se them all the ability to see them as a slideshow or some way that shows smaller images would be useful. Tough to find one quickly without going from one end to the other. 

![image](https://cloud.githubusercontent.com/assets/6060985/5778806/cd2aa24c-9d95-11e4-9796-1f6c850b2f14.png)

Album is here: http://dev-hernehill.gotpantheon.com/photo-albums/traders

**Comment by pmackay** [comment]
Fixed to show smaller thumbnails

**Comment by GilesGibson** [comment]
Thanks, much better
