### ISSUE TITLE
Photo album - breadcrumb menu not working

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#440]
Dev site. 

Tried to use the breadcrumb menu at the top of traders gallery to go back to the parent gallery. Not able to.

![image](https://cloud.githubusercontent.com/assets/6060985/5778857/30ff731a-9d96-11e4-9e28-21853f591e41.png)

**Comment by pmackay** [comment]
Will add Galleries in front. We're not planning a "landing page" for albums so there is no valid link for that bit.

**Comment by GilesGibson** [comment]
OK, just going back to galleries would be acceptable... for now....

**Comment by pmackay** [comment]
Fixed on dev.
