### ISSUE TITLE
Bulk upload being limited to 20 images

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#441]
Dev site.

http://dev-hernehill.gotpantheon.com/photo-albums/underpass-art-display

Tried uploading 44 files. Only 20 uploaded.

If this is a limit then we should state on the upload screen - "limited to 20 images per upload" or similar.

**Comment by pmackay** [comment]
Suggested text added to Images field http://dev-hernehill.gotpantheon.com/node/add/ol-photo-album.

**Comment by GilesGibson** [comment]
Thanks
