### ISSUE TITLE
Error codes on screen

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#443]
Dev site

Refresh gives this (goes on for ages), also on home page:

![image](https://cloud.githubusercontent.com/assets/6060985/5779281/787a3754-9d99-11e4-8ea7-4fd212c3fe59.png)

**Comment by pmackay** [comment]
Yeah, erm, you see that message about "unable to allocate memory" - thats
probably cos this site is too big for basic Pantheon. Hmmm.....

**Comment by GilesGibson** [comment]
had a hunch that we would hit the ceiling soon.

**Comment by GilesGibson** [comment]
need to clear caches? May have been after I did the bulk upload?

**Comment by pmackay** [comment]
Fixed now I think, will doing ongoing improvements to remove any duplicate modules and reduce overall memory footprint. 

And obviously, no more features allowed ;-)

**Comment by GilesGibson** [comment]
OK, no more features, except for the ones that are ongoing, and maybe a few more little ones, plus a few real humdingers...
