### ISSUE TITLE
News article tags: label and tag styling not lining up correctly

### ISSUE THREAD

**Issue by djwesto** [folklabs/hernehill.org.uk#446]
In News Articles, I am trying to get tags to sit under their label but to line up inline, rather like they are in this screenshot:

![screenshot 2015-01-21 17 03 56](https://cloud.githubusercontent.com/assets/702685/5840705/8409e872-a18f-11e4-991e-0688ca196b5c.png)

However, I cannot for the life of me figure out how to get them to do this.
Any chance you could look into this, @pmackay?

**Comment by pmackay** [comment]
Tweaked a bit.

**Comment by djwesto** [comment]
On *live-* I'm now seeing this layout which is looking good now:

![screenshot 2015-01-23 12 07 00](https://cloud.githubusercontent.com/assets/702685/5874350/629ef4a6-a2f8-11e4-8749-ff8bd2484207.png)
Any chance you could get the div containing the "0 Comments" to sit flush with the left edge of the area, rather than in line with the profile name and publishing date and time above? Not a biggy but would clean this up.

Nice one – out of interest, could you tell me what you changed?

**Comment by pmackay** [comment]
See https://github.com/folklabs/hernehill.org.uk/commit/3e93dd33714d2ca72337163c6f5707954bd1ad36.

**Comment by pmackay** [comment]
done.
