### ISSUE TITLE
Review styling of site alert/info messages

### ISSUE THREAD

**Issue by pmackay** [folklabs/hernehill.org.uk#447]
Consider:

* Increase the size of text in all notifications
* Increase spacing above and below them to set them further apart from normal site content
* Increase colour contrast between notifications and the normal site content
* Perhaps introduce stronger graphics to draw more attention to them

**Comment by djwesto** [comment]
Here's a comp showing a much more visible styling for messages:
* Error = Pink
* Info = Green
* Alert = Blue

![screenshot 2015-01-27 15 46 01](https://cloud.githubusercontent.com/assets/702685/5921463/0607101a-a63c-11e4-8fed-527514a7c626.png)

And here's how they'd look in-situ on the home page:

![screenshot 2015-01-27 15 46 14](https://cloud.githubusercontent.com/assets/702685/5921489/30ada7de-a63c-11e4-891c-b50f72cbe38e.png)

Stand out enough, @GilesGibson ?

**Comment by GilesGibson** [comment]
much better, thanks

**Comment by djwesto** [comment]
@GilesGibson and @pmackay

Please can you both keep an eye out on the site alert messages over the coming days for me? I need you to alert me if you see any problems with the new styling I just introduced. I was going to make them solid colours as in the visual above but that was simply too much when the lonnnnnnnnng Drupal error messages filled up screen after screen so I went with a white alert message background with coloured border.

They're not always displayed and we haven't got StyleGuide module working any more so it's hard to preview them. If you see any problems let me know on this issue but I'm closing for now.
