### ISSUE TITLE
Community page - maps initial view

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#450]
I know Herne Hill is a big place but it would be nice to start the map display (when you first select map tab) with a slightly smaller map...

![image](https://cloud.githubusercontent.com/assets/6060985/5841944/dca70fd8-a198-11e4-9f53-20ecab4e2118.png)

**Comment by pmackay** [comment]
Done a small fix on this, but also the map automatically shapes around the points. There were a couple of test entries with address data that put them in Scotland. Have removed.

**Comment by GilesGibson** [comment]
Ta
