### ISSUE TITLE
Unable to edit draft alert

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#451]
Dev platform.

Created an alert, saved as draft. Tried to go back to it to edit it, under my page, tab for draft content - it was listed, I clicked on it and got:

![image](https://cloud.githubusercontent.com/assets/6060985/5842424/8f957500-a19c-11e4-9dda-e7aaaaf7fc7a.png)

Cannot find where I would edit it and correct any mistakes.

**Comment by pmackay** [comment]
Link works better to content on draft content table. I see this:

![screen shot 2015-01-22 at 08 50 41](https://cloud.githubusercontent.com/assets/115115/5852764/db162ae8-a213-11e4-8e86-1a18e65a1d54.png)

and can click Edit to change.
