### ISSUE TITLE
Unable to login for new users

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#452]
Dev site. Yan, one of the beta testers can still not login to the site. He is not receiving the authentication emails. I had asked him (and others) to review the site again but he cannot do anything more than browse.

**Comment by pmackay** [comment]
The best option for this would be to actually start paying for the live
site, get the domain working and setup the proper email address. We could
put a lock on the whole thing so it cant be spidered. And mark it as beta.
Thoughts?

**Comment by GilesGibson** [comment]
Happy with that.

What difference would it make? Given that we had awful problems with the
existing site being unable to get the emails through for about 6 months or
so.

From:  Paul Mackay <notifications@github.com>
Reply-To:  "folklabs/hernehill.org.uk"
<reply+005c7bb9641ca62e0abf57a02de1f755c1067b4502ffc56e92cf0000000110d88c8b9
2a169ce0349460b@reply.github.com>
Date:  Thursday, 22 January 2015 10:01
To:  "folklabs/hernehill.org.uk" <hernehill.org.uk@noreply.github.com>
Cc:  Giles Gibson <giles.gibson@originaltg.com>
Subject:  Re: [hernehill.org.uk] Unable to login for new users (#452)

The best option for this would be to actually start paying for the live
site, get the domain working and setup the proper email address. We could
put a lock on the whole thing so it cant be spidered. And mark it as beta.
Thoughts? 

‹
Reply to this email directly or view it on GitHub
<https://github.com/folklabs/hernehill.org.uk/issues/452#issuecomment-709971
08> .

**Comment by pmackay** [comment]
I still dont really understand the old site issues. But if we can setup a
decent email gateway, then the fact that the emails would come from the
same domain as the site is a big deal in terms of whether something is
considered spam or not.

**Comment by GilesGibson** [comment]
OK, happy to risk it. The existing site seems to have calmed down at the moment, not too many support issues to do with being unable to logon.

**Comment by pmackay** [comment]
Would you want the current migrated content on live, if we set that up?

**Comment by GilesGibson** [comment]
Just had another report on login issues from another test user. 

![screen shot 2015-01-22 at 10 28 17](https://cloud.githubusercontent.com/assets/6060985/5854067/c8a572fc-a221-11e4-932e-6abbb17f7101.png)
![screen shot 2015-01-22 at 10 28 08](https://cloud.githubusercontent.com/assets/6060985/5854071/cfe44548-a221-11e4-9ed7-40b819943fea.png)

Two screen shots of what they received. Clipped due to phising alert. They have managed to continue and will see if the login is activated.

**Comment by pmackay** [comment]
Would you want the current migrated content on live, if we set that up?

**Comment by pmackay** [comment]
Right, I've tested email and changed some settings.  Now get a full unclipped message, from the right email address, no phishing message. Plain text for now. Please ask others to test and remember to tell them the username/password to just access the site.

**Comment by GilesGibson** [comment]
please migrate all content to live if you can, otherwise the cupboard will look bare.

**Comment by pmackay** [comment]
Was migrated.
