### ISSUE TITLE
Image upload - what is focus rectangle?

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#453]
Dev site. Tried uploading an image to the site for display (alerts). Got this:

![image](https://cloud.githubusercontent.com/assets/6060985/5853818/1a5b3c9c-a21f-11e4-8856-7433712cf196.png)

No idea how to change the focus rectangle - what is it? Needs some explanation on screen or at least a hint as what to do.

**Comment by pmackay** [comment]
You can draw a box on part of the image to define which bit it will focus on when cropping. It has an explanation below (which we cannot change).

**Comment by GilesGibson** [comment]
The explanation explains what it does, not how to do it.
