### ISSUE TITLE
Alerts - edit draft not showing image

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#454]
Dev site. I edited the draft of the alert. Uploaded an image. went to look at it in draft and got a black box where the image should be:

![image](https://cloud.githubusercontent.com/assets/6060985/5853859/7bccf9fc-a21f-11e4-8f86-000467a9a75b.png)

**Comment by pmackay** [comment]
Can you try with another image? I tried and it looked ok.

**Comment by GilesGibson** [comment]
OK, lets leave it, if it happens again we can create a new issue.
