### ISSUE TITLE
Gallery not showing image and therefore not clickable

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#455]
Dev site. Some galleries (last ones) are not showing an image on the thumbnail. This also means that you cannot click on the box as a whole, just the title of it in order to get access to it.

![image](https://cloud.githubusercontent.com/assets/6060985/5853908/fa2507cc-a21f-11e4-8f5c-2f20ff911668.png)

**Comment by pmackay** [comment]
Thats because I removed the images field from Gallery, because its now in Photo album. But all the existing content had its content wiped out. Please test with new content.

**Comment by GilesGibson** [comment]
If you click on the title of the thumbnail "test campaign Title Photo Gallery" you then get the two albums that I uploaded the other day.

**Comment by pmackay** [comment]
Fixed.
