### ISSUE TITLE
Unable to see where to edit my personal profile address

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#456]
live site.

The login asks me to update my personal profile in the address1 line. I clcik on the oink and get this:

![image](https://cloud.githubusercontent.com/assets/6060985/5872846/d76800a4-a2e7-11e4-8d7a-448982b38feb.png)

No idea which tab to use for editing my address, none seem to show it.

**Comment by pmackay** [comment]
Try Edit > Personal info.

**Comment by GilesGibson** [comment]
OK, lets send people there then, or give better instructions i.e. click here, then this menu, then this tab, then edit the box called "address line 1".

**Comment by pmackay** [comment]
Good idea, have updated link to go directly to the right edit page.

**Comment by GilesGibson** [comment]
Great, always good to send users where you asked them to go....;-)
