### ISSUE TITLE
Move frontpage forum panel to sit under featured stories listing

### ISSUE THREAD

**Issue by djwesto** [folklabs/hernehill.org.uk#459]
Question for both @pmackay and @GilesGibson:

The Featured Stories listing on our front page only features 3 stories along with the spotlighted top three in the carousel. That means that the front page layout currently looks like this:

![screenshot 2015-01-26 11 10 37](https://cloud.githubusercontent.com/assets/702685/5899809/03db6e00-a559-11e4-8889-a873aeda0b9b.png)

You can see at the bottom, we have the Recent Discussions and Recent Tweets panels both running off the end of the page while the news stories peter out much earlier – this creates a vacuum at the bottom of the central column which will only grow worse as soon as a couple of adverts and an alert are showing in the right hand column.

My suggested solution to this issue is to move the "Recent Discussions" panel into the central column to sit underneath the main featured news listing which will then allow the righthand column content to sit higher up the page.

What do you think, @GilesGibson ?

**Comment by djwesto** [comment]
Incidentally, in case it helps, here's a quick comp showing how those forum posts might look in a wider listing – we could explore adding in more fields if it was deemed helpful:

![screenshot 2015-01-26 13 18 27](https://cloud.githubusercontent.com/assets/702685/5900161/e6ad5a6e-a55d-11e4-876e-ae12907ae187.png)

**Comment by GilesGibson** [comment]
Lets run with the recent discussions bit under the news items and see how it goes. we could always increase the number of news items displayed to say 6 or so as an alternative.

**Comment by djwesto** [comment]
That would work too – was just trying to keep within the existing number of highlighted stories. I guess there's a question which we'll need to be flexible around as to the number of highlighted stories you want to keep on the home page at any one time.

**Comment by djwesto** [comment]
@pmackay want me to make this adjustment or would you prefer to?

**Comment by GilesGibson** [comment]
A nice management panel setting number of stories, where adverts are allowed, how many tweets to show.... would be fab. Means we wouldn't have to ask you every time a change was wanted. 

#justsayin

**Comment by pmackay** [comment]
Yes, that's what the buttons in the black bar at the page bottom are for!
The power of Panopoly :)

**Comment by GilesGibson** [comment]
OK, good. Can it easily change the number of news stories displayed then? Do we need to factor in some sort of site help text to cover this?

**Comment by djwesto** [comment]
Now moved to middle column and regenerated the Feature – now just needs slightly tweaked styling.

**Comment by djwesto** [comment]
Now fixed and pushed. Please check http://dev-hernehill.gotpantheon.com/ and sign-off if you're happy with this, @GilesGibson:

![screenshot 2015-01-27 17 05 13](https://cloud.githubusercontent.com/assets/702685/5922842/b3e92d30-a646-11e4-8fe8-d5866b5fbea9.png)

**Comment by GilesGibson** [comment]
lets roll with that and see what the feedback is.
