### ISSUE TITLE
Upload of image in Alert dialogue box - cannot use Focus Rectangle

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#460]
www.hernehill.org.uk. Tried to edit the draft of an alert that I had cerated. Uploaded a new image, went to Focus Rectangle and tried to click on image to define a rectangle, no use, image just dragged away from page, no rectangle offered.

Description box underneath Focus Rectangle does not state how the box should be filled? Stuck.

**Comment by pmackay** [comment]
Tested this, seemed ok. Cannot reproduce. Lets review?

**Comment by GilesGibson** [comment]
OK
