### ISSUE TITLE
Events - how to display previous month

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#462]
www.hernehill.org.uk site.

I waas trying to display the previous months events.

![image](https://cloud.githubusercontent.com/assets/6060985/5904657/0569b280-a582-11e4-87b4-3584652655cb.png)

Tried hitting display all, didn;t work, just reset it to today, cannot figure out how I would get the month to display for a previous (or next) month. Not intuitive.

**Comment by pmackay** [comment]
How about http://dev-hernehill.gotpantheon.com/events/month/2014-12? Also note the calendar pages are now tabs on events page on dev.

**Comment by GilesGibson** [comment]
OK, just need simple way of showing users how to get the different views. Can we have a menu to click? Day/week/month?

**Comment by pmackay** [comment]
Yes, they would click on the month/week/day view and then click the
back/next links at the top of each of those views.

**Comment by GilesGibson** [comment]
but the month/week/day tabs are not visible - see screen grab above.

**Comment by pmackay** [comment]
They are on dev http://dev-hernehill.gotpantheon.com/events
