### ISSUE TITLE
events - showing comments box open

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#463]
www.hernehill.org.uk

Clicked on an individual event. It shows the details but not the start date and end date or location. Bit confused.

![image](https://cloud.githubusercontent.com/assets/6060985/5904721/8b0b9dfe-a582-11e4-8a3d-8a6746651d31.png)

Also - the add comment box is by default open - can we by default not show it open, just the "add comment" icon that will then allow the dialogue box to open out. I assume that the creator of the event could decide if they wanted comments to be allowed?

**Comment by pmackay** [comment]
Link for event please?

Not going to do closed comment box for now.
