### ISSUE TITLE
How to get back to calendar view from detailed view

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#464]
www.hernehill.org.uk

I was trying to get back to the standard view of whats on by using the breadcrumb trail.

![image](https://cloud.githubusercontent.com/assets/6060985/5918233/3cdec39e-a61e-11e4-83a8-e79655445b1d.png)

I cannot get back to where I came from (standard whats on view) unless I go via the main menu at the top of the screen.

**Comment by pmackay** [comment]
The position of these pages has changed on dev. Could review there or wait
for it to be pushed.

**Comment by GilesGibson** [comment]
Had a look at dev, tabs fine. What happened to the filters for type of event - childrens, outdoors, meeting etc?

![image](https://cloud.githubusercontent.com/assets/6060985/5919113/5a187842-a628-11e4-8f50-84225f33dfe4.png)

**Comment by pmackay** [comment]
There are only filters on the "upcoming" view.

**Comment by GilesGibson** [comment]
Hmm, strange as we had discussed filters for what's on extensively. The filters should be available for any type of view, not just the upcoming.

**Comment by pmackay** [comment]
We have discussed extensively, but its a more complex feature. Could you please raise a new issue or check the backlog for filtering on calendar views? And close this if thats ok?
