### ISSUE TITLE
site never completes a refresh

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#465]
www.hernehill.org.uk

I have noticed recently that the browser tab shows a spinning wheel next to the site name, it never stops spinning. As a result the browser refresh option is never shown. Bottom of the browser window has a message saying that it is waiting for something or other from the site.

Seems to be stuck somewhere and never quite finishing serving up the page to the browser.

Site still seems to work though.

**Comment by pmackay** [comment]
What browser? Do you see this on all browsers? Cannot really reproduce.

**Comment by GilesGibson** [comment]
Chrome is the main one I use.

Safari seems to be OK on the refresh although I don¹t know how it displays
that it is waiting for something.

From:  Paul Mackay <notifications@github.com>
Reply-To:  "folklabs/hernehill.org.uk"
<reply+005c7bb97ce0a3373df14332fd935cca3818694f8f21be4a92cf0000000110df5b8b9
2a169ce0350a4fb@reply.github.com>
Date:  Tuesday, 27 January 2015 13:58
To:  "folklabs/hernehill.org.uk" <hernehill.org.uk@noreply.github.com>
Cc:  Giles Gibson <giles.gibson@originaltg.com>
Subject:  Re: [hernehill.org.uk] site never completes a refresh (#465)


What browser? Do you see this on all browsers? Cannot really reproduce.

‹
Reply to this email directly or view it on GitHub
<https://github.com/folklabs/hernehill.org.uk/issues/465#issuecomment-716511
78> .

**Comment by pmackay** [comment]
Could you show me tomorrow?

**Comment by GilesGibson** [comment]
will review and feedback if it happens again.
