### ISSUE TITLE
Registration/Login problems for new users

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#475]
Yan has just reported that he still cannot login on the www.hernehill.org.uk site. I am unsure if he has tried getting another password reset but will update as soon as I know.

**Comment by pmackay** [comment]
Do you have more information about what the problem is?

**Comment by GilesGibson** [comment]
I have emailed Yan again, awaiting his reply.

**Comment by GilesGibson** [comment]
Yan has checked his spam folder, still nothing there. @pmackay Can we wipe his account and ask him to start again?

**Comment by pmackay** [comment]
What is his account name or email?

**Comment by GilesGibson** [comment]
address = 'jh-testing@mybtinternet.com' or similar

**Comment by pmackay** [comment]
OK, removed now.

**Comment by GilesGibson** [comment]
Yan has tried again, screenshot below. Still no joy.

![capture hh testing](https://cloud.githubusercontent.com/assets/6060985/6041938/aed52384-ac78-11e4-9365-7ad5959d87a8.JPG)

**Comment by djwesto** [comment]
More details needed before we can solve this issue I reckon...
* How is he accessing his email? Outlook on Windows, on a BT Internet online system etc?
* What computer does he have - Windows PC, Mac?
*What sort of level of skills does he have - basic, intermediate, advanced?
* I assume other mail messages *are* being received at jh-testing@mybtinternet.com? I can't find a single Google reference to the server "mybtinternet.com" and there's no website showing up at that server either, which doesn't on its own mean that the server doesn't exist, but it does suggest there might be a problem with the email he's using. I've just emailed him to check. Is this an email account he checks regularly @GilesGibson? If not, I might need to ask you to call or email him on a more conventional address to request that he checks this test inbox.
* Following on from this, if it's not his email that's the problem then I wonder if he needs to whitelist the new domain *hernehill.org.uk* needs in order for the emails to be received. If this is the case, we might need to investigate getting the address approved somehow – never had to do this before so would need a bit of research. Who's the domain registered with Giles?

**Comment by djwesto** [comment]
BTW, I just registered a test user on live- (the hernehill.org.uk site) and my confirmation email arrived in Gmail pretty-much instantly.

**Comment by GilesGibson** [comment]
Yan changed his email address to the current one a while back. It is the one we use in the google groups as well. I have been emailing him regarding the new site and other stuff without major hassles. 

It is very similar to the spate of problems we had for about 6 months with the existing site. The authentication email simply didn't get through, it appeared that there was an issue between ISPs not allowing emails from the web site that sent the emails, need to have their SPF(?) record amended etc. It went away about 3 months ago although we do get the occasional issue cropping up but that tends to be more that their spam folder ate the email.

It may be that we are experiencing the same issue again with the new test site.

**Comment by pmackay** [comment]
We should probably try a different gateway...

**Comment by djwesto** [comment]
So are you able to look back into what solved this "SPF record" (or whatever it's called) issue last time? Any documentation or process you went through would be much appreciated – we can look into it but, if you've already solved this once before, it would help to know how.

**Comment by GilesGibson** [comment]
Never managed to do anything, problem just started to go away, hence the frustration that it has come back like a bad rash.

**Comment by djwesto** [comment]
So you never got around to doing any of this stuff, @GilesGibson?

Looks like we might need to do this since we're setting up and entirely different domain:
https://support.google.com/a/answer/33786?hl=en

**Comment by GilesGibson** [comment]
I looked in to the issues and the process, it needed some code in the web site, endless liaison with our ISP/hoster and more techie stuff that to be honest I didn't have the time to work through. I was hoping that the new site would have been there etc etc. Looks like we would have to add the spf records if the google doc is anything to go by, be worth working through doing it, be useful elsewhere.

**Comment by pmackay** [comment]
@GilesGibson can you please chase to see if this is resolved with those who've had problems?

**Comment by GilesGibson** [comment]
Am meeting with Yan tonight to review new site. Get his ideas about
strategy, ideas, etc.

From:  Paul Mackay <notifications@github.com>
Reply-To:  "folklabs/hernehill.org.uk"
<reply+005c7bb90a878fefccea0f63e6b0f2f358f23f1d6934bb4a92cf0000000110fd83cd9
2a169ce0356b9fd@reply.github.com>
Date:  Thursday, 19 February 2015 10:58
To:  "folklabs/hernehill.org.uk" <hernehill.org.uk@noreply.github.com>
Cc:  Giles Gibson <giles.gibson@originaltg.com>
Subject:  Re: [hernehill.org.uk] Registration/Login problems for new users
(#475)


@GilesGibson <https://github.com/GilesGibson>  can you please chase to see
if this is resolved with those who've had problems?

‹
Reply to this email directly or view it on GitHub
<https://github.com/folklabs/hernehill.org.uk/issues/475#issuecomment-750337
51> .

**Comment by GilesGibson** [comment]
yes, login problems now resolved for Yan.
