### ISSUE TITLE
How to migrate old galleries?

### ISSUE THREAD

**Issue by pmackay** [folklabs/hernehill.org.uk#476]
@GilesGibson @djwesto do you think we should now migrate old galleries into Photo albums, and then someone can manually create some galleries to include albums afterward?

**Comment by GilesGibson** [comment]
yup, a bit of granularity that can then be put together would be good. What is the down side though?

**Comment by pmackay** [comment]
just that no galleries will be visible on the Galleries page until some are setup. But albums would be there in people's profiles.

**Comment by GilesGibson** [comment]
OK, so a few hours of time by someone would start to sort the albums into potential galleries?

**Comment by pmackay** [comment]
yes.
