### ISSUE TITLE
No users except admin are able to create / edit Photo Albums

### ISSUE THREAD

**Issue by djwesto** [folklabs/hernehill.org.uk#477]
Permissions issue discovered with Photo Albums:

Just logged in as *chriswells*, rather than *Admin* and tried to Add a new photo album to my own profile. Instead of being allowed to upload images, I was redirected to an Access Denied page.

This appears to be because none of the permissions for Photos Albums have been set in Permissions yet. I'm loathe to touch these so best if @pmackay takes this on.

**Comment by pmackay** [comment]
fixed on dev.
