### ISSUE TITLE
Remove empty field group on New User Registration page

### ISSUE THREAD

**Issue by djwesto** [folklabs/hernehill.org.uk#479]
@pmackay I'm seeing a weird empty field group at the bottom of the User Reg page: 

It has a Field group label of "Main Profile" but contains no fields or labels.

![screenshot 2015-02-04 11 58 32](https://cloud.githubusercontent.com/assets/702685/6040044/4a52a4b2-ac65-11e4-9bc2-a07234e8fc5e.png)

Not a huge bug – more a cosmetic usability problem which might cause confusion. Feel free to backlog or V1.1 this if you wish.

**Comment by pmackay** [comment]
Removed.

**Comment by djwesto** [comment]
Confirmed. Closing.
