### ISSUE TITLE
Unable to access admin area

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#482]
hernehill site, content transferred.

Logged on as whatsup. Unable to figure out where the admin area is to manage users, send out a mass mailout to all traders, or event managers etc. 

WIll there be a dedicated menu bar for users that have admin permissions? How will this all work?

**Comment by pmackay** [comment]
In user migration you're only getting editor role. I've added admin role to your profile so you can see admin bar now.

Will add editor role so they can see admin bar.

**Comment by GilesGibson** [comment]
thanks
