### ISSUE TITLE
Unable to apply to create new group

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#486]
hernehill.org site. Standard user.

Community page. clicked on "add new group" and got an error page:

![image](https://cloud.githubusercontent.com/assets/6060985/6283961/fe535c3e-b8e2-11e4-9f5d-4998ba35af46.png)

It should allow access to at least the dialogue box to request a new group be created etc.

**Comment by pmackay** [comment]
fixed on http://dev-openlocal.pantheon.io/groups
