### ISSUE TITLE
Venue creation - need button to show maps

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#488]
The text explaining how to create a venue - refers to checking that a place doesn;'t already exist by going to the map. How would a user get there? can we have a button or at the least a hyperlink embeded in the text.

![image](https://cloud.githubusercontent.com/assets/6060985/6284014/d4c3349c-b8e3-11e4-8c03-4a5fecd706a6.png)

**Comment by pmackay** [comment]
Implemented at http://dev-openlocal.pantheon.io/node/add/ol-place.
