### ISSUE TITLE
Unable to apply to have a services listing

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#489]
hernehill.org. stabndarduser

Tried clicking on "add a service" button. Got error page:

 
![image](https://cloud.githubusercontent.com/assets/6060985/6306076/3443181c-b928-11e4-9d32-d6a2dee7f843.png)

**Comment by pmackay** [comment]
Fixed on http://dev-openlocal.pantheon.io/services. Goes to new Issue page.
