### ISSUE TITLE
Remove google analytics from the admin dashboard

### ISSUE THREAD

**Issue by pmackay** [folklabs/hernehill.org.uk#492]
Have just discovered that the Google analytics dashboard view depends on https://www.drupal.org/project/chart which depends on a Google charts API that will be removed in April. Propose we remove this analytics reporting function.

FYI @GilesGibson

**Comment by GilesGibson** [comment]
I am not sure what we use this feature for? Is it to feed our google analytics dashboard? If so then this is a problem as we use the analytics quite a bit. Be good that the new site inherits all the old site info and seamlessly continues so we can do track back and review historic performance.

**Comment by pmackay** [comment]
Analytics will still be collected, you just have to go view them in the
Google Analytics website, thats all.

**Comment by GilesGibson** [comment]
Ah, where else were they being shown?

**Comment by pmackay** [comment]
In one of the admin views on the HH site itself.

**Comment by GilesGibson** [comment]
OK, probably wont miss it too much then

**Comment by pmackay** [comment]
Done but not yet pushed to all places.
