### ISSUE TITLE
display of upcoming events

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#493]
Just checking to see that the left hand column of upcoming events will display the small thumbnail image if there is one in the original event?

![image](https://cloud.githubusercontent.com/assets/6060985/6327988/272aa13e-bb5a-11e4-9572-4e82256ea480.png)

**Comment by pmackay** [comment]
Potentially but lets review in 1.1.

**Comment by pmackay** [comment]
Reviewed but space is very small for that size of image. Closing and lets see what kinds of images are added to events...
