### ISSUE TITLE
Assemble a listing of all known local event venues and places for import

### ISSUE THREAD

**Issue by djwesto** [folklabs/hernehill.org.uk#495]
@pmackay & @GilesGibson, what are we doing about assembling a listing of local event venues and places? Currently, because the existing site doesn't have these in its database, we are looking at this for the primary view when an Event host tries to add a venue to their event:

![screenshot 2015-02-23 16 54 07](https://cloud.githubusercontent.com/assets/702685/6332351/a04da68e-bb7c-11e4-95f7-fd933d1ee7bc.png)

@GilesGibson, will you be taking this on and, if so, how do you plan to do it? I would like to see as many venues added in there as possible.

Likewise, Places should also be added where sensible so that we have a nicely-populated site before launch.

@pmackay how should this data be supplied to you for import?

**Comment by pmackay** [comment]
For importing, can these just be added manually?

**Comment by GilesGibson** [comment]
We could do some of the work on populating venues prior to changeover. However, if the site will be wiped before content transfer what happens to our work?

Places - are these not being populated by services listings? If so I am happy initially to email all service listing providers and encourage them to update their entries as a matter of course. The more they can do the better.

**Comment by djwesto** [comment]
@pmackay Depends how many venues there are. Do I detect some resistance to importing them into the database via some sort of CSV? Fair enough. I'm just providing a warning that there's currently nothing in there so when I come to set up an Event, I have nothing to select from and, as a standard user, I can't see any way to add a venue either.

**Comment by pmackay** [comment]
If there are going to be lots, then we could look at CSV. But if not,
probably simpler to enter by hand.

Places are not the same as Services (Businesses). Places are for stuff like
churches, schools.

**Comment by pmackay** [comment]
@GilesGibson the list of places (as opposed to services) is not going to get created by any imported content. Do you want to create a CSV for import or is it enough to just add place items manually over time?

**Comment by GilesGibson** [comment]
Lets add places over time.
