### ISSUE TITLE
maps not displaying on details pages

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#504]
hernehil.org.

maps in whats on and servcies are displaying as blanks.

**Comment by pmackay** [comment]
What's on - are there any events associated with a venue? If not, it wont show anything.

Services - somewhere the map tab got removed, I've restored it on here http://dev-openlocal.pantheon.io/services/map which shows a map because there are 2 services with addresses.

**Comment by GilesGibson** [comment]
tried editing a venue, added in my postcode to the venue, still got a greyed out map. Is this because it has been fixed on dev but not updated to hernehill yet?

![image](https://cloud.githubusercontent.com/assets/6060985/6348165/80c285a2-bc15-11e4-9f69-549e661a4d70.png)

**Comment by pmackay** [comment]
This is known (probably also raised before) but fix still needed. Maps have
proved quite finicky.

**Comment by GilesGibson** [comment]
OK, I will leave it with you. Issue raised and logged.

**Comment by pmackay** [comment]
Ah, realise you meant the small maps per piece of content. My earlier comment about was about the larger maps. Please do paste links when you raise issues as it really helps to know which page you're referring to :)

**Comment by pmackay** [comment]
I think this is affected by having an accurate address. http://dev-openlocal.pantheon.io/services/biz-2 and http://dev-openlocal.pantheon.io/places/school are rendering ok.
