### ISSUE TITLE
venues map displaying huge area

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#506]
hernehikll.org. 

venues amp displays most of UK. IS this because there is an errant venue location? If so can we delete it and only show the SE24 area as a default diplsay.

![image](https://cloud.githubusercontent.com/assets/6060985/6347797/96153ad8-bc12-11e4-91b9-470975c5da37.png)

**Comment by pmackay** [comment]
Please could you check for an earlier issue on this - I think its a
duplicate.

**Comment by GilesGibson** [comment]
It probably is a duplicate (cannot find the first one) . Before you just deleted the errant location I think. If it has come back then we need to add it to the list of things to do for the migration, or delete the naff listing. Not quite sure how you want to log issues that had been solved before but have come back again. Just re-opne the last one?

**Comment by pmackay** [comment]
Re-opening is always good. For now I've added an item to the migration plan to check map content after migration.
