### ISSUE TITLE
Define list of place types

### ISSUE THREAD

**Issue by pmackay** [folklabs/hernehill.org.uk#509]
@GilesGibson, Places need a taxonomy list of the types of locations - do you have any list like that based on work done with the tunnel map or similar?

I've started a list here https://docs.google.com/spreadsheet/ccc?key=0AvwNdTyma3n1dENoTk5zbXRzUUFKcGM0LTloWENlS3c#gid=7 but would be great to fill it out more.

**Comment by GilesGibson** [comment]
I have shared the images of the map. Not quite sure what else would help from that.

**Comment by GilesGibson** [comment]
couldn't get access to the google link - get an error message back from google, file is a mess or something like that.

**Comment by GilesGibson** [comment]
am chasing the list of local traders in their shops.

**Comment by pmackay** [comment]
I've just checked that list, but its the traders list, not the types of things we'd enter as Places. We'll just make up a simple list for now that we can add to.
