### ISSUE TITLE
Twitter feed to show pictures

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#510]
hernehill.org.

Is it possible/easy to have the twitter feed on the left hand side of the home page to also show images if there are any? Twitter does it and it would be good to encourage more images on the front page. Makes it look better.

**Comment by djwesto** [comment]
It might not necessarily look better. It might just look busier. But I take it you mean that you want to see the images users have tweeted and not just their avatars?

I tried to check out what might be possible with this Twitter view we're using to drive the Twitter feed on the homepage but the UI is now switched off for performance purposes so @pmackay is your man to tell you whether or not we can include images.

_NB:_ I've actually created a new Github label – **feature-request** which we can use to assign to your non-critical feature changes.

**Comment by GilesGibson** [comment]
The twitter feed at the moment has been improved since the comment above, we now get the avatars which makes it look better. If it is easy to add any image the tweet had then great but agree that too much "noise" gets distracting. However, twitter is moving towards a far more visual tool than just 140 characters.

**Comment by djwesto** [comment]
I'd be very interested in any links to that last point about Twitter becoming more visual but generally I think I'm going to close this one now.
