### ISSUE TITLE
Remove "Draft" phase from editorial workflow

### ISSUE THREAD

**Issue by pmackay** [folklabs/hernehill.org.uk#519]

**Comment by pmackay** [comment]
Cannot reproduce. @djwesto could you comment or give screenshots of the difference for a regular user of moderation of news v alerts? Yesterday we seemed to think Alerts worked differently.

**Comment by djwesto** [comment]
We've worked through to show where this occurred and I can now see that Carolina never clicked the dropdown and that led me to assume she would be able to set her own article to be published but @pmackay has explained that she would not have been able to publish. Therefore, I vote we keep the tool visible on the Moderation tab, and that we follow @pmackay's advice that we remove the "Draft" stage of moderation (pending his investigation of whether the "Save as Draft" functionality still works without that edit state).

Then we will change the wording of the "Publish" button on the node edit pages to instead say "Send for moderation" which will clarify that functionality.

**Comment by djwesto** [comment]
Just realised this should be assigned to @pmackay because it's about removing the "Draft" moderation phase from the editorial workflow. Have also changed the title of this issue to reflect that.

**Comment by pmackay** [comment]
Going to defer, think this is duplicate anyway.

**Comment by pmackay** [comment]
Read more about WB Moderation, found that Draft and Published are required. Suggest we try idea here https://github.com/folklabs/hernehill.org.uk/issues/536#issuecomment-87213384
