### ISSUE TITLE
Edit Create Event venue selection help text

### ISSUE THREAD

**Issue by djwesto** [folklabs/hernehill.org.uk#521]
When creating a new Event, once you get to the section where you have to assign a Venue to your event, you see the following help text:
>If your event takes place in a physical space, please select it from our list of Herne Hill venues. Click "Select a venue" to show a list of all possible venues. Choose a suitable venue and click "Submit". You can browse the list of available venues to see what is available.

This text is great but neglects to mention that you need to ensure your event Venue or Place has already been created or you won't be able to select it. I suggest changing this to:
> If your event takes place in a physical space, check to ensure you can select it from [our venue list of available spaces](http://www.example.com). Click "Select a venue" to show all possible venues. Then select your event venue and then "Submit".

**Comment by djwesto** [comment]
If, as @GilesGibson has just asked, we need to also offer users the chance to add a new Place before they select one in the create Event page, we need to provide them with a link through to the Add Place page too – preferably in a pop-out page which won't take them away from their current page.

> If your event takes place in a physical location, make sure it's already in our [list of available venues](http://www.hernehill.org.uk/venues). Select "Add item (venue)" to choose your venue from our listings and click "Submit". If we don't already have it, save this page (click *Save as draft*) then [Add a new place] (http://www.hernehill.org.uk/node/add/ol-place) to create a new venue before returning here to finish.

**Comment by djwesto** [comment]
@GilesGibson did you approve this new help label wording?

**Comment by GilesGibson** [comment]
lets see what the testers say.

**Comment by djwesto** [comment]
This *was* from an issue that arose during Carolina's test and it was a problem then – your testers have spoken and the microcopy has been found wanting. It still looks like this:

![screenshot 2015-03-09 10 43 57](https://cloud.githubusercontent.com/assets/702685/6553492/3ed72592-c649-11e4-93f7-4cd67db2daa4.png)

**Comment by GilesGibson** [comment]
Yes, hence you have wonderfully suggested a change of text. I had assumed you had updated the site with your proposed new text, hence then seeing what the testers thought.

**Comment by pmackay** [comment]
Updated on live.
