### ISSUE TITLE
URL for hernehill.org.uk could be forwarded to www.hernehill.org.uk

### ISSUE THREAD

**Issue by djwesto** [folklabs/hernehill.org.uk#524]
Please could we have hernehill.org.uk forwarded to www.hernehill.org.uk because right now if I don't type in www. the site reports an error.

![screenshot 2015-02-25 15 16 56](https://cloud.githubusercontent.com/assets/702685/6373260/6533de66-bd01-11e4-93ca-22ee0270c419.png)

**Comment by pmackay** [comment]
fixed.
