### ISSUE TITLE
Event category filter title needs improving

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#526]
hernehill.org

display on left - filter of events, needs to be clearer in how to use the category filters. Suggest "filter by category'

![image](https://cloud.githubusercontent.com/assets/6060985/6374179/1dd1b8ee-bd07-11e4-8486-b05530d1d984.png)

**Comment by pmackay** [comment]
@djwesto do you think this title change would make sense for other left side category panels?

**Comment by pmackay** [comment]
Changed on http://dev-openlocal.pantheon.io for news, events, groups.
