### ISSUE TITLE
New field needed on Create Event to describe the "Type of event" it is

### ISSUE THREAD

**Issue by djwesto** [folklabs/hernehill.org.uk#529]
We agreed on 25 February that we need some way of setting a new Event to be for:
* Over 18s only
* Child-friendly
* Meeting
* Outdoor event

Along with possibly others as-yet unthought of.

![screenshot 2015-02-25 17 10 58](https://cloud.githubusercontent.com/assets/702685/6375783/48224dde-bd11-11e4-9112-abeb584b03a3.png)

**Comment by pmackay** [comment]
So this was agreed not a new field, but just add items to existing one right?

**Comment by pmackay** [comment]
Closing as existing field to be used.
