### ISSUE TITLE
Move "Recent discussions" block back under main news listing on homepage

### ISSUE THREAD

**Issue by djwesto** [folklabs/hernehill.org.uk#530]
Please could we move the "Recent Discussions" block back to sit under the main news listing on the homepage.

![screenshot 2015-02-25 17 55 10](https://cloud.githubusercontent.com/assets/702685/6376702/7560feca-bd17-11e4-9aed-94f75007c6d9.png)

**Comment by pmackay** [comment]
Fixed on OpenLocal site.
