### ISSUE TITLE
Should moderation states be changed to only "Needs review" and "Published"?

### ISSUE THREAD

**Issue by pmackay** [folklabs/hernehill.org.uk#532]
@djwesto @GilesGibson thoughts?

**Comment by GilesGibson** [comment]
as long as people can edit their published document and then either publish direct again or submit for moderation then fine.

**Comment by pmackay** [comment]
Punting this to v1.1, lets see how much of an issue it is.

**Comment by pmackay** [comment]
Dupe of #519.
