### ISSUE TITLE
Sitemap is not populated with all pages or configured to include site sections

### ISSUE THREAD

**Issue by djwesto** [folklabs/hernehill.org.uk#534]
I've just spotted that the sitemap is not populated with any content beyond the frontpage. Without it we will have trouble with SEO issues. I've included this in the migration plan although we'd also benefit from having a chat about it beforehand.

![screenshot 2015-02-27 18 02 03](https://cloud.githubusercontent.com/assets/702685/6418173/c63a3b38-beaa-11e4-8aa7-4c7b54ba18f9.png)

We'll need to configure it here during the content import on this page: http://www.hernehill.org.uk/admin/config/search/sitemap

**Comment by pmackay** [comment]
Can you check http://www.hernehill.org.uk/sitemap and see if anything else is missing that is important?  Most things added now.

**Comment by djwesto** [comment]
Well done – great work, @pmackay. A few things:
* "Footer menu" should probably be removed, since it's referencing only the Sitemap right now.
* I can't see any other standard content pages. Is that because we're no longer using a book structure to publish them and the sitemap module can't see them (i.e. they don't appear in the menu tree any more)? 
* As to the other site sections referencing "Categories", is this one (see screengrab) complete? It seems like it's missing quite a few taxonomy terms. And where would I go to change the lines where it says things like "This is a sitewide taxonomy of categories to organize the content on your site!" or "Forum navigation vocabulary":
![screenshot 2015-03-09 10 00 02](https://cloud.githubusercontent.com/assets/702685/6552946/3b02556e-c643-11e4-8ad9-68525240db97.png)

Other than that language, I think we can probably close this issue.

**Comment by pmackay** [comment]
Have removed footer menu.
Pages are only referenced via a menu I think. Plus we need to add more pages :)
The categories should get fully updated when we migrate...
