### ISSUE TITLE
News item on front page

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#538]
hernehill.org.uk site. Whatsup as user.

I created a news item - car crash in HH. It displays on the news page. I was uncertain how to get it to the front page. I selected "highlight story" but it still doesn't display on the front page. Could you confirm the process for promoting a news story to the front page. Is it something that a normal user can do? If not how do they request their story gets on the front page.

![image](https://cloud.githubusercontent.com/assets/6060985/6480787/6c0a04ba-c24f-11e4-9f89-df08a7ed49c2.png)

**Comment by pmackay** [comment]
Please check the admin manual, does that help?

**Comment by GilesGibson** [comment]
as a user, where would the admin manual be? 
Also been looking for the help button/file. Where has that gone?

**Comment by pmackay** [comment]
It's a Google doc we shared with you. Users wouldn't have access, but editors should.

**Comment by GilesGibson** [comment]
OK, I think I have found the document -I also found the user guide. 

The admin guide just says click the highlight link, which I had done but it still didn't display on the front page. 

Couple of issues this throws up. 

How do we get the user guide available at all times to the users i.e. where is the help button.

How do we get the admin guide available to admin level people - needs a button/link etc on the site for them.

**Comment by djwesto** [comment]
Guys, the Admin Manual is even less finished than the User Guide... Sorry.
@GilesGibson I will try to do some work on this but I am a little overwhelmed. I need to know which specific guidance you'd want first. Any chance you could add priority areas into the doc (just as bullet points) listing the *most* important areas up-front you'd want users to see?

@pmackay, we're just talking about uses with the *Editor* roll here aren't we? When I log in as editor, I see this, so can I assume I only need to document these tasks for Editors:
![screenshot 2015-03-04 11 12 05](https://cloud.githubusercontent.com/assets/702685/6482593/66ff27ec-c25f-11e4-9be4-ae0a28ab8801.png)

**Comment by GilesGibson** [comment]
I have added at the end of the document a brief list of typical tasks that we will need to know how to do. I think that you have covered quite a few areas in the document, yes it could be made easier to follow with screen grabs but the backbone is there, thanks.

**Comment by pmackay** [comment]
@GilesGibson I've updated the admin manual with a section on how to configure and send newsletter messages to sub-groups. See if it helps.

**Comment by pmackay** [comment]
Discovered that another module that provides the "cycle" method for slideshows (as opposed to other transition methods) needed enabling, which is now done, so slides are showing.

**Comment by GilesGibson** [comment]
It certainly makes it look big....

![image](https://cloud.githubusercontent.com/assets/6060985/6503973/ddfa543c-c329-11e4-8a6d-3faea50857e5.png)


May need tweaking a bit. Text is all over the place...

**Comment by pmackay** [comment]
Ah, new problem, that's happening when there are multiple highlights, but not on FF which is why I didnt notice earlier.

**Comment by pmackay** [comment]
Have added fix for title positioning above image. OK to close?

**Comment by GilesGibson** [comment]
Looks much better, thanks.
@djwesto is the text meant to be that large? If that is part of the design then great, I will bow to your infinite better judgment.

**Comment by GilesGibson** [comment]
@pmackay  Just checked again.The photo obscures the "commnents" tag underneath. May need to tweak.

![image](https://cloud.githubusercontent.com/assets/6060985/6523198/7a128946-c3e5-11e4-8ddb-8abc6644ec08.png)

**Comment by pmackay** [comment]
@GilesGibson could you clear your cache and refresh a couple of times?

**Comment by pmackay** [comment]
FYI, I've submitted some other changes to help with this.

**Comment by GilesGibson** [comment]
moved to 1.1 to check that the display is still OK.

**Comment by pmackay** [comment]
Can this be closed please?
