### ISSUE TITLE
Category for service listing

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#540]
Can we add in a category for the service listing of "market stall". We need to start contacting all the market stall operators to get them to create a service listing on the new site. People can then find them via filtering on the categories. 

Not sure how we maintain/edit the category list. If it could be something  available to site admins it would reduce requests to the geniuses.

**Comment by pmackay** [comment]
Please check new section on Taxonomies in https://docs.google.com/document/d/1RPXdN2rqi9OdBeBaTMWzIwVVGAFMbvnqI_m8ZLIkeWU/edit#. Does that cover it?

**Comment by GilesGibson** [comment]
Great. I went to the section on the web site, I think I created a new category for business listings. It didn't appear in the services section for categories. What did I do wrong?

**Comment by GilesGibson** [comment]
OK, looks like it has come through now. No idea what happened, maybe needed to be left alone for an hour.
Thanks

**Comment by pmackay** [comment]
The service taxonomies only show terms if there is 1 or more businesses
with that term. I added one of the services to that category so then it
appeared.

**Comment by GilesGibson** [comment]
Great, makes sense, kind of.
