### ISSUE TITLE
Unable to get on to new test site due to lock screen

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#541]
hernehill.org.uk. Gerry Evans was wanting to access the new site to test. She was using a Lambeth computer on their network. She was unable to get past the pantheon "curtain". Tried putting the username and password in "hh", "hh" to no avail. After three attempts it locked her out.

She is running Windows, probably IE browser.

She can see the dev site though.

Is this just a Lambeth internal network issue or browser issue? If the pantheon anti-spammer screen was removed I assume she can use it as normal?

**Comment by pmackay** [comment]
Can you or anyone else test this in the council?

**Comment by GilesGibson** [comment]
I will try next time I am in there.

**Comment by GilesGibson** [comment]
reported back that access is now OK. may have been the lock screen that messed up Lambeths system.
