### ISSUE TITLE
Service listing - category filter to be alphabetically listed

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#544]
hernehill.org.uk

Feedback from testers. They fid  the category listing on the services page awkward to use as it is sorted by numbers, not alphabetical. Can we re-do this and get it sorted alphabetically by default.

I am also assuming that the number of categories will be reduced to the smaller set that we discussed before.

**Comment by pmackay** [comment]
Fixed.

Categories will be handled as part of #149.
