### ISSUE TITLE
Change button label & alert message text on moderated content types

### ISSUE THREAD

**Issue by djwesto** [folklabs/hernehill.org.uk#545]
We need to change the button label microcopy and alert messages for all content types which get submitted to editors for moderation before being published.

On buttons, we currently use the label "Publish". This should be changed to something like "Submit to editors".

On alert messages we use "Your news article has been created" or similar. This should change to "Your news article has been submitted to the editors".

**Comment by GilesGibson** [comment]
I went through all the content and noticed a few items that were in draft. There was an event waiting for moderation plus a few things that users had struggled with and left as draft versions - Blue Patch for one. 

What this tells us is that the process for going from text, save as draft or submit for publication, get published, is still not clear enough to the users.

**Comment by pmackay** [comment]
How is this different to #536?

**Comment by GilesGibson** [comment]
it isn't, it is the same, within reason..
