### ISSUE TITLE
Comments icon in wrong place

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#547]
hernehill.org.

"Comments 0" icon on the first news story is up next to other text. Subsequent news stories it is placed under image. Can we have it the same for all?

![image](https://cloud.githubusercontent.com/assets/6060985/6616337/e321d586-c8a4-11e4-806a-973389d73187.png)

**Comment by pmackay** [comment]
Duplicate of #487. Think we need to handle this in new theme.
