### ISSUE TITLE
Colour difference in "more" icon

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#548]
hernehill.org..
news page. Icons on news stories - first two had dark green colour for the "more..." icon, following ones had light green

![image](https://cloud.githubusercontent.com/assets/6060985/6616363/30229776-c8a5-11e4-87ef-cb62146c4d1f.png)

**Comment by pmackay** [comment]
This is intentional - it depends if you've read the content or not.

**Comment by GilesGibson** [comment]
Ah, ok.
