### ISSUE TITLE
Forum section - remove old topic of web site

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#553]
new site.

As we have created a new topic for new web site issues can we either delete or hide the old topic for the web site as it used to be (RIP)? may confuse people as to where to post comments etc.

**Comment by pmackay** [comment]
So you're not bothered about old content that was posted in there?

**Comment by GilesGibson** [comment]
it was only relevant to the old site. we have a new topic running now. If we need to get access we can go to the old site.

**Comment by GilesGibson** [comment]
Can a super admin type person be able to delete this in the future please? Saves having to ask you?

**Comment by pmackay** [comment]
You already can - please have a go. Some docs are in the admin manual on taxonomy. Shout if not clear.

**Comment by GilesGibson** [comment]
Had a look through the admin manual, nothing mentioned. I couldn't see an obvious place that was mentioned in the taxonomy document either. If you let us know where within the site the Forum admin stuff is then I can add examples to the admin manual.

**Comment by pmackay** [comment]
Have added Forums to the list of taxonomies in admin manual. Link is there too.

**Comment by GilesGibson** [comment]
OK, have deleted the old web site feedback topic. Rephrased the new one. I have briefly updated the admin manual, the use of the term Taxonomy is alien to most general admin people, need to revisit this language in the guide.
