### ISSUE TITLE
Assign categories to Community Groups

### ISSUE THREAD

**Issue by djwesto** [folklabs/hernehill.org.uk#554]
@GilesGibson needs to assign categories to errant community groups with none at the moment:
- http://www.hernehill.org.uk/groups/brixton-live
- http://www.hernehill.org.uk/groups/poets-corner-residents
- http://www.hernehill.org.uk/groups/step-local

I haven't the faintest idea what they are.

**Comment by GilesGibson** [comment]
logged on as admin

tried to delete group "step local",same result for "Brixton Live"

Got this error

![image](https://cloud.githubusercontent.com/assets/6060985/6834358/81c55222-d32b-11e4-9746-f228e0e906a1.png)

**Comment by pmackay** [comment]
@GilesGibson this is a weird thing with Drupal, even when deleting an item, it wants all required fields to be filled out. The problem is that the groups have been imported without a category, but it is a required field (should it be?). So to delete it, just click a category checkbox first :)

**Comment by GilesGibson** [comment]
great, old empty groups now deleted.
