### ISSUE TITLE
Existing photo albums cannot be saved

### ISSUE THREAD

**Issue by pmackay** [folklabs/hernehill.org.uk#557]
They show message “The file used in the Images field may not be referenced.”

**Comment by pmackay** [comment]
@GilesGibson this is also fixed. You can now edit albums migrated from old site and associate them with a gallery. Please could you create some new galleries for this?

**Comment by GilesGibson** [comment]
@pmackay I would appreciate a para or two being added to the tech manual that guides me as to how galleries now work - who can edit what, where they are published etc. Difference between group galleries, personal galleries and site gallery. I can then elaborate on the documentation and do the necessary housework.

**Comment by pmackay** [comment]
Closing as have added some notes to admin manual (https://docs.google.com/document/d/1RPXdN2rqi9OdBeBaTMWzIwVVGAFMbvnqI_m8ZLIkeWU/edit#heading=h.8aji6827fzvi) and this issue is not about docs.
