### ISSUE TITLE
How can I see all content posted?

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#559]
New site
logged on as admin

I have just published an event after checking in moderation. I went to whats on but couldn't see it there. However I couldn't remember the date it had been for so may have missed it.

How can I view all the latest site postings in a list? I am sure there is an admin menu item showing this somewhere. Then I may be able to find out where the entry has got to.

**Comment by pmackay** [comment]
@djwesto could you look into this re the docs?

**Comment by pmackay** [comment]
@GilesGibson I think you're using it but all content visible at http://www.hernehill.org.uk/admin/content.

**Comment by pmackay** [comment]
Think this is resolved now.
