### ISSUE TITLE
Submitting an event - flow needs improving

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#560]
new site

Feedback from user who tried to submit an event:

I created an account and I submitted my event, but I can’t find it on your website, I think it’s only the “draft” of my article. Do you have to approve it before?

Need to look at the use of language to walk them through the process.

**Comment by pmackay** [comment]
@djwesto, what is the state of docs regarding creating events?

**Comment by djwesto** [comment]
Documentation about Events creation is on its way to being completed. But there's a gap in there where I wasn't clear myself on how the moderation process worked. I will try creating a test event and fill in the blanks for moderation.

**Comment by GilesGibson** [comment]
Great, happy to contribute to the docs as well. Not sure where the user dioc lives though, have only been doing the admin manual.

**Comment by djwesto** [comment]
Moved to V1.1

**Comment by pmackay** [comment]
I think this is covered by several other issues related to submitting and finding content.
