### ISSUE TITLE
Whwere has a news item gone  to?

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#563]
new site. logged in as admin

There has been a news item submitted - the profile of canopy beer. I didn't see it in the moderation list but I did get access via a url from twitter. It is awaiing publishing. I published it. Checkled to see if it was on fron tpage or news items, neiother. It has appreared on "whats hot" 

![image](https://cloud.githubusercontent.com/assets/6060985/6850404/f84ca0b2-d3d0-11e4-8075-2c03be7bf158.png)
though

**Comment by GilesGibson** [comment]
OK, despite refreshing the page a lot it hadn't appeared then, it has now. Still strange why it didn't appear in the moderation list for admin.

**Comment by pmackay** [comment]
This could just be a cache problem? Pretty sure thats why it didnt appear
immediately on front/news pages. Not sure about moderation queue.

**Comment by GilesGibson** [comment]
glad "what's Hot" is on the ball eh?

**Comment by pmackay** [comment]
You betcha, smokin'....

**Comment by pmackay** [comment]
closing this, lets see if other stuff doesnt appear for moderation...
