### ISSUE TITLE
Whats the strange zero

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#564]
new site, front page - Whats Hot.

Not sure why one item has a colured Zero next to it. Just curious.

![image](https://cloud.githubusercontent.com/assets/6060985/6851332/4e4e2f12-d3d6-11e4-94a1-5d7b7442d530.png)

**Comment by pmackay** [comment]
For some unknown reason, '0' values get shown when new content is setup, but once the values start to change it seems ok, so usually goes away (and has done now).
