### ISSUE TITLE
Venues and places - need explanatory text

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#566]
new site. Logged on as admin: http://www.hernehill.org.uk/venues

Be useful to have some explanatory text about what is being displayed and the criteria of being a venue. Same for when places are displayed as a map. Confusing about the difference.

![image](https://cloud.githubusercontent.com/assets/6060985/6852101/97adc786-d3da-11e4-94db-0a8ee56215bd.png)

**Comment by djwesto** [comment]
@GilesGibson Could you possibly scribble something down here now as a suggestion for each piece of UI text and I can then wordsmith it?

Cheers

**Comment by GilesGibson** [comment]
If I can remember what the difference is I will.

**Comment by pmackay** [comment]
Closing as we're moving to Locations.
