### ISSUE TITLE
Errant Forum in the Forum section

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#567]
new site:

![image](https://cloud.githubusercontent.com/assets/6060985/6853773/07416986-d3e5-11e4-9e2c-931ae7443b3c.png)

Not sure what Herne Hill Forum is doing as a forum section. I think it used to be at the top of the old site. I think it could just be deleted.

See also #553

**Comment by pmackay** [comment]
Removed.
