### ISSUE TITLE
Event appears to display but site states it is in draft?

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#568]
new site
Admin login.

The whats on shows the Minnows class as being an event:

![image](https://cloud.githubusercontent.com/assets/6060985/6854543/e78b609c-d3e9-11e4-8fe0-5f577ec588ae.png)

However, when the admin user clicks on the event it seems to show it as the revision state is in draft:

![image](https://cloud.githubusercontent.com/assets/6060985/6854566/09ab1758-d3ea-11e4-998e-1bd2ed1f2bc9.png)

The tab showing is Published tab. Not sure what is going on here.

**Comment by pmackay** [comment]
I think this is an issue with migration - the content is published and visible, but the moderation status is not matching that. Either dont worry about it or set to published.
