### ISSUE TITLE
Creation of new group

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#571]
New site. Logged on as admin

I have no idea how to allow/create a new group on the site. I have a new user who wants to create a group, they clicked on the request group button, got a message saying access denied. Is this from the group creation side or that maybe they are not logged in?

Nothing in the admin manual for how to do this bit – I am happy to write the text but have no idea where to start from.

**Comment by djwesto** [comment]
I'm afraid the admin manual isn't even started yet Giles. Paul's now away for the weekend so not sure when he'll be getting to this.

Without being able to see what the user is doing, it's hard to be able to deal with this query. Please will you ask them to check whether they are logged in or not? I just tried to create a group while I wasn't logged in and the site wouldn't let me – sent me to an Access Denied page too. Then I logged in and tried to do the same and was successful.

Please would you explain to them that they can't create a group if the site doesn't know who they are.

**Comment by GilesGibson** [comment]
I did ask them, hopefully they will try again. Be good to have a better message than "access denied". Could we change it to "You need to be logged in to do this"

**Comment by djwesto** [comment]
As with everything, please log an issue for a new change and we'll add it to the list.

**Comment by GilesGibson** [comment]
the admin manual has been started, the google doc is what I am using at the moment. Happy to start adding to it.

**Comment by GilesGibson** [comment]
error message was down to not being logged in. We need to change the text, creating support hassles.

**Comment by pmackay** [comment]
I've setup a custom access denied page http://www.hernehill.org.uk/access-denied and the content is shown (with a generated title) when that happens. Feel free to edit the page for a better message.

**Comment by djwesto** [comment]
Sorry, @GilesGibson. Back to the original issue. Are you saying you _weren't_ logged in now?

So have you tried to create a new group once you _are_ logged in? In your email to us just now you said you: 

> still no idea how to create a group for someone. I am happy to edit up the admin guide but need to know where the page is for creating a new group and allocating the administrator to it.

Have you tried navigating to this page: http://www.hernehill.org.uk/node/add

Alternatively, click the "Add content" button at the top of your screen and you'll be taken to the same page.

Next, select "Group" and let us know if you are then taken to the Create Groups page. I was when I was just logged in a second ago as Admin.

Cheers

**Comment by GilesGibson** [comment]
I was logged on as admin. However I had no idea where on the admin menu I should go and what I should do to create a new group. I also do not get any notifications that there has been a request to create a new group although that may have been sorted with the info@hernehill.org.uk working. 

I will go to the node/add page and see what that is. Will update admin manual as well.

**Comment by GilesGibson** [comment]
Do I assume that the author of the group is also the administrator of the group?

Do I add a new person into the group membership via the group edit function, member and then into a drupal page where I think I can change the profile of the user to be administrator - is this correct?

**Comment by pmackay** [comment]
I think the author would be the admin.

Go to Group tab on a group and click "Add people" to add more members.
