### ISSUE TITLE
Service lister cannot edit their entry

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#575]
new site

Had a phone call from Bob-a-job. He has a listing as a handyman http://www.hernehill.org.uk/services/bob-job-fast-friendly-efficient-creative-and-professional-bespoke-service

He logged on to edit his setup etc. He went to save and got the error page, he thinks it was a 504 or 505 error. The message was about the site being fixed etc.

**Comment by pmackay** [comment]
Opened his entry as him, had no problem saving it. Did he have some validation message after editing? Could he try again?

**Comment by GilesGibson** [comment]
He has now reported that he can edit his page (and has done) but when he clicked on +request business listing button he got the page error screen (the one we edited/wrote). he said he was logged on at the time. Not sure why he clicked on the button as he already had a service listing but that shouldn't have stopped him clicking again and applying for another. Something still strange about permissions for this button.

**Comment by pmackay** [comment]
Tested "request business listing" button logged in as test user. Got to the "Create Issue" page. Seems ok.

**Comment by GilesGibson** [comment]
I have just tested it again with a newly created standard user and it seems fine. However, here is the screenshot that he sent. Looks like he was logged in and got the error page.

![image](https://cloud.githubusercontent.com/assets/6060985/6947430/2f172bf8-d89f-11e4-9203-a21780a054ea.png)

**Comment by pmackay** [comment]
OK so he wasnt logged in. Sounds like this works as expected.

**Comment by GilesGibson** [comment]
Ah, but if you look at the screen shot, he was logged in.

**Comment by pmackay** [comment]
OK I've updated this page to allow for this
http://www.hernehill.org.uk/access-denied.

You still get that page if you are logged in but not allowed to do
something.

**Comment by GilesGibson** [comment]
so why wouldn't he be able to request a service listing again?

**Comment by pmackay** [comment]
Found a button that had a wrong link. Have fixed now.

**Comment by GilesGibson** [comment]
Brill! got there in the end, many thanks.
