### ISSUE TITLE
Draft of news article does not show title block

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#576]
new site. Logged on as admin.

I wrote a news item. went to edit it but it does not show the title bar in the edit window, just the body of the text. I wanted to edit the title but could not see it.

![image](https://cloud.githubusercontent.com/assets/6060985/6896654/a492ac9c-d6e5-11e4-8160-d03281b5fbb2.png)

**Comment by pmackay** [comment]
I see the title just above though:

![screen shot 2015-03-31 at 09 10 58](https://cloud.githubusercontent.com/assets/115115/6914762/fd23c09e-d785-11e4-8b44-8eb142fc0589.png)

**Comment by djwesto** [comment]
I'm confused. What's the actual problem here? @GilesGibson did you perhaps screengrab the wrong page? The image you've added doesn't show what the problem really was to me and @pmackay seems to be saying there is a title visible anyway. Please re-supply a screengrab showing what the problem was.

**Comment by GilesGibson** [comment]
yes, probably a bit of confusion. The title of the news item is above the menu items, seems strange and disjointed. Not a great preview of what it looks like. If possible to change then great.

**Comment by pmackay** [comment]
I dont think moving the title would be straightforward. Suggest closing this if immediate issue resolved.
