### ISSUE TITLE
News item not displaying on front page

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#578]
new site. Logged on as admin

I created a news item - about the hustings meeting. Saved and published it. Then went back to edit it a couple of times, saving and publishing each time. It appears on the carousel but not as one of the latest news items on the front page. I <think> I saw it after the first time I saved it but the subsequent edits did not display. Tried refreshing but still nothing.

![image](https://cloud.githubusercontent.com/assets/6060985/6898464/52ab618c-d6f2-11e4-9c52-0531f1baf096.png)

**Comment by pmackay** [comment]
As discussed, news items added to Highlights do not also appear below.

**Comment by djwesto** [comment]
To echo @pmackay's point, why would you want a story appearing in the both the carousel _and_ the news article listing below it? It would be daft and a wasted opportunity to show more articles..
