### ISSUE TITLE
trader list - may be missing many traders

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#579]
new site. logged on as admin.

I checked out the user roles, selected the filter to just show all users with the status of trader, only listed about 40 or so. Given that we have around 200 services listed what happened to all the other users that are also service owners i.e. traders?

**Comment by pmackay** [comment]
I've double checked, there are about 39 users with "Services manager" role in the old site. So I think these have transferred ok. Are you sure all traders had the role assigned?

**Comment by GilesGibson** [comment]
Every service listed had an owner.       Did that automatically make them a services manager?  If not can we extract all their contact details and add them in to the mailing list?  In the future will a service owner be added to the list automatically?

**Comment by pmackay** [comment]
Each node will have an owner, but it looks like that didnt automatically
make them a service manager on the old site.

**Comment by djwesto** [comment]
So, if it's not possible to identify them any other way, is there a way that @GilesGibson could supply a list of all the service managers from the previous site we could use to assign that role in the new site? Quite complicated otherwise.

**Comment by GilesGibson** [comment]
maybe this is why one trader couldn't edit their own service listing. If it cannot be done with a script then it will have to be a manual edit of every service listing. to do this it would help if there was a simple way of extracting each service listing name and the login name that was used to create it. Then it just needs a few hours of cut and paste, something I can do over Easter.

**Comment by pmackay** [comment]
Traders should be able to edit their own listings without having a role
assigned anyway. The role is (currently) just to be able to email them all.

**Comment by GilesGibson** [comment]
agreed. We just need to be able to contact that user group. Each trader should only be able to edit their own entry. Is this easy?

**Comment by pmackay** [comment]
Yes, should be doable now.

**Comment by pmackay** [comment]
@GilesGibson are you happy to contact traders now or are there any other blockers?

**Comment by GilesGibson** [comment]
I assume anything more than plain text is a non-runner at the moment?

**Comment by pmackay** [comment]
Closing because mail editing is covered by #587.
