### ISSUE TITLE
Traders listed as group managers

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#586]
new site

Just checking how the groups work in mass mailings. It would appear that the "traders" group is the "group managers". Is this correct? if so I am confused, I had thought that the traders were, traders.

http://www.hernehill.org.uk/admin/config/system/mass_contact

![image](https://cloud.githubusercontent.com/assets/6060985/6922725/4651e8ec-d7c5-11e4-848e-8e3756b202eb.png)

**Comment by pmackay** [comment]
Fixed the traders one. Feel free to created others. 

FYI, the email subject will start with the category above in `[ ]`. Do you want them to start with `Herne Hill`?

**Comment by GilesGibson** [comment]
can it just be left blank so we can know exactly what the subject line will look like?

**Comment by GilesGibson** [comment]
I have added "group managers" to the group managers category - is this correct?

I have also removed traders from the content editors category as we want to email people who can edit/create content separately from the pure traders. Does this make sense?

**Comment by pmackay** [comment]
I've disabled including the category then, as requested.

**Comment by GilesGibson** [comment]
Is there a way of splitting event editors i.e. anyone who has unrestricted ability to create an event from those that have unrestricted ability to create a news item? Need two categories ideally. If hard to do then no problem, leave as content editors.

**Comment by pmackay** [comment]
Could you comment on https://github.com/folklabs/hernehill.org.uk/issues/582#issuecomment-88166988? Closing this one.
