### ISSUE TITLE
Issue raised by user - not sure what it is

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#592]
new site.logged on as admin.

I have had a look at the content list. It shows a few items that are listed as "issues". I didn't receive any email about an issue, there is no content awaiting moderation so am a bit confused as to what is going on here. Is it a new post? Why is it described as an issue?

Content screen:

![image](https://cloud.githubusercontent.com/assets/6060985/6939306/4973f378-d863-11e4-98e7-4468afb52a36.png)

One of the "issues".

![image](https://cloud.githubusercontent.com/assets/6060985/6939301/36862916-d863-11e4-9753-817d3e66b58b.png)

**Comment by pmackay** [comment]
Have added a new section https://docs.google.com/document/d/1RPXdN2rqi9OdBeBaTMWzIwVVGAFMbvnqI_m8ZLIkeWU/edit#heading=h.bju318hayqnd about this. Please review.

**Comment by GilesGibson** [comment]
Thanks for updating the admin manual. What is of concern is that we may have taken a step backwards in usability in this area. As we are using a general purpose issue page to record any issue there is no easy way to get users to provide the relevant information at the first attempt. Ideally we would want a simple custom form that is displayed if they select the option of "request a service listing". We could then ask them to fill in a field that was the name of the business they wish to have and another simple field that asks a bit about the business. we can then see if it is relevant and if so, create a new listing (ideally with a button that jumps straight to the create content area and populates the correct field with the service listing name. If it could also add in the login name of the requestor as the author that would be good too. 

Maybe all of this isn't easy to do, somewhere between what we have at the moment and that option would be OK for now. 

With the current system there is more tasks for the admin team to do and more that the users has to do than the old site. 

Current tasks for admin:
1. check to see if an issue has been raised.
2. read through the content that the user has sent in, may be relevant to creating a service listing, may not.
3. May need to email back to the users for clarification about their business.
4. Go to create content section, choose create group. Cut and paste from issue page into new service listing page. Cut and paste from issue page the users login name and paste into new service listing page.  Save new listing.
5. email user with details of their new service listing, the name etc and URL.

**Comment by pmackay** [comment]
Can you describe what was done on the old site? You've never outlined how
that worked.

**Comment by GilesGibson** [comment]
It was completely non automated. A bit fiddly etc. The background to creating a listing, tips, encouragement about how to write it etc was in the guide document we sent them. Most of that is now all on the help text bits on the service listing screen that they now get.
1. user emailed in a request to info@.
   2.we emailed back the guide to getting a listing.
   3.user sent login name and title of service listing
2. we created service listing (cut and paste from their email) and made user the author.
3. site sent email direct to them.
4. we did quick reply to tell them it was set up.

**Comment by pmackay** [comment]
I'm not sure how anything is taking a step backwards here?

**Comment by GilesGibson** [comment]
more tasks for admin people, more confusion/tasks for end user. Awkward to contact the user when viewing the issue page, no obvious way to email back, unless adding a comment will generate a prompt to them automatically. Lots of cut and paste which would be good if we can minimise. Was really hopping to make this process easier.

**Comment by pmackay** [comment]
Sounds like building the Issue type was a waste of time. Shame not to have
identified this earlier.

**Comment by GilesGibson** [comment]
I think that the issue work isn't wasted. It is just that ideally, if they select the request service listing it would generate a different form. Having all the issues listed for admin team to see is a step forwards. Just not sure how to use it for service listings (and group creation requests either). 

If a comment is made to the issue raised will the user get a prompt email telling them that their issue has had a reply and they can "click here to read it" type of prompt?

**Comment by pmackay** [comment]
I think emails should get sent. May need more testing.

**Comment by pmackay** [comment]
Will try to look at this when we can - we have a backlog issue to improve it.

**Comment by GilesGibson** [comment]
OK, happy with that. In the mean time I can update the admin manual. Could you confirm the query about the comment issue, raised above? Be quicker than me testing a series of scenarios.

**Comment by pmackay** [comment]
Users should see this:

![screen shot 2015-04-01 at 23 17 46](https://cloud.githubusercontent.com/assets/115115/6953996/59d5360c-d8c5-11e4-9e07-4ada528357ce.png)
