### ISSUE TITLE
Permalink on services - how does it work?

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#594]
New web site
logged on as admin.

Having a look at a service - there is the permalink field. 

![image](https://cloud.githubusercontent.com/assets/6060985/6941276/56d72914-d876-11e4-9db2-d63bfc805b71.png)

Not quite sure how a user is supposed to make use of it. The first half of the URL is fixed, the second half  is auto-filled. However it is nigh on impossible to copy it to the clip board and it doesn';t respond to clicking the fixed bit. Bit stuck as to how the auto-generated link is meant to work.

**Comment by pmackay** [comment]
Why do you need to change this?

**Comment by GilesGibson** [comment]
probably dont, just puzzled as to how to make use of it.

**Comment by pmackay** [comment]
Closing ;-)
