### ISSUE TITLE
Service listing - not showing categories to select

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#595]
new site.
logged on as admin
http://www.hernehill.org.uk/node/15091/edit

Trying to figure out where this service listing has got to. It got imported from the old site. I went to have a look at it and checked to see what had been done. I went to edit the entry and see what category it had been filed under (if any). No option offered to add in a category.

![image](https://cloud.githubusercontent.com/assets/6060985/6941460/32856ace-d878-11e4-8055-b9cf45d6e717.png)

**Comment by pmackay** [comment]
Fixed. This item is a Place, not a service. Have added Places categories.
