### ISSUE TITLE
How to create a new service listing via the issue report

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#596]
new site
logged in as admin.

Went to dashboard and saw that a few issues had been raised. Two requests for a servcie listing. 

![image](https://cloud.githubusercontent.com/assets/6060985/6941648/835e095a-d879-11e4-8fb6-54e38be3a3b0.png)

One already has a listing, brought across from the old site. The other requested a new listing. 

What is the process to follow to create a new service listing from the issue that has been raised? 

I select the issue and have a look, apart from a comments box that is the only way of "replying". 

How much hassle would there be in having a more streamlined process - the request comes in, we can say yes, or no (and give reasons) and then if yes, generate a service listing?

**Comment by pmackay** [comment]
Have added a new section https://docs.google.com/document/d/1RPXdN2rqi9OdBeBaTMWzIwVVGAFMbvnqI_m8ZLIkeWU/edit#heading=h.bju318hayqnd about this. Please review.
