### ISSUE TITLE
Issue comment - when replied to does not appear on the site

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#599]
new site
logged on as admin.

A comment was added to an issue raised - about a new service listing being required. The comment was sent out. The end user replied directly to the email they received - from "Herne Hill". This therefore bypassed the issue handling system on the web site so no audit trail as there afterwards.

Is there a way the replies can go back to the comment system? Should we edit the text that gets sent out and encourage them to click on the link and answer the comment there?

**Comment by pmackay** [comment]
Emails cannot go back into the comment. Way too complex at this point. 

Realistically are users likely to use the Issues correctly? Or just resort to email?

**Comment by GilesGibson** [comment]
Looks like they just use reply.

**Comment by pmackay** [comment]
Closing as we're not likely to do anything about handling email replies to update the site and issues deemed not important.
