### ISSUE TITLE
Issue closed - email not very informative

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#600]
new site
logged oin as admin.

Issue was changed from being active to being closed. The email that was sent out to the admin team (I think) was:

See
http://www.hernehill.org.uk/issues/test-create-new-group-people-who-need-help-computers.

If possible could we have some more helpful text around this email i.e. something about the status of the issue now being closed, thanks for raising this, let us know if there is anything ekle etc etc.

be great if it was something that we could edit in the future.

**Comment by pmackay** [comment]
Could you please provide the text you would like?

**Comment by pmackay** [comment]
If issues are being dropped, can this be closed?

**Comment by GilesGibson** [comment]
Yup
