### ISSUE TITLE
Event shopwing up in Whats On that is in draft mode

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#602]
new site
logged on as admin.

http://www.hernehill.org.uk/events/month

take a look at the event "silver Tuesdays fun and fitness" on the 23rd. the one that only has 1.00p.m. as the date. Go have a look - it states that the status is draft, not published. Check with the one that they did later and that has a picture and the status is "published". 
![image](https://cloud.githubusercontent.com/assets/6060985/6952860/66cbb370-d8bd-11e4-9e0c-deed5031d654.png)

Not sure why there is a draft version showing in the calendar.

**Comment by pmackay** [comment]
All migrated content from old site is basically in Draft state but is published in terms of visibility. Suggest deleting the one you dont want...

**Comment by GilesGibson** [comment]
If it is a one off then fine. Lets hope it isn't going to show up too much. Happy to leave this one.
