### ISSUE TITLE
Problems in changing an image in the news item - publish/draft not updating

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#603]
new site
admin user.

A news item was published with one picture.

![image](https://cloud.githubusercontent.com/assets/6060985/6959554/3cce7a8a-d912-11e4-9ce7-8a7f410024e0.png)

It appeared in the news section.

The news item than was updated with a different picture and re-published. The carousel showed the correct image but the news page had the old one. No amount of page refreshes seemed to solve the problem.

![image](https://cloud.githubusercontent.com/assets/6060985/6959588/9f418748-d912-11e4-93f6-9e9d37f917fd.png)

Now, after a few minutes the news page has updated itself. It looks like there is a huge lag between what the carousel shows and the news page. This lag gives the impression that the site is faulty, it causes confusion. IS there any way the delay in a news page showing an item can be reduced?

**Comment by pmackay** [comment]
Is this resolved by clearing the cache?

**Comment by GilesGibson** [comment]
probably. Happy top elave for now.
