### ISSUE TITLE
query coincerning oublish versus unpublished

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#604]
new site
admin user

The content page shows a forum post as being unpublished (Dulwich Spring Fair).

![image](https://cloud.githubusercontent.com/assets/6060985/6959695/7ad75508-d913-11e4-868c-b278fbe8b09b.png)

However when the forum is viewed the post is there:

![image](https://cloud.githubusercontent.com/assets/6060985/6959688/6c3b6714-d913-11e4-9b58-3cb8107b065a.png)

Not sure why the content page shows incorrect info or am I misunderstanding what the content page is about?

**Comment by pmackay** [comment]
I think rigbydan has published a 2nd one that has "Saturday" in title, whereas the unpublished one just has "Sat" so they are different posts.
