### ISSUE TITLE
Change of text re: Business listing plus button not working.

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#607]
new web site
feedback from users.

Can we update the text on the background that is shown with the +request a business listing" button.

At present the button "about business listing" returns an error. Can we sort this and have some text added to whatever should pop up that explains that a business listing is the same as a servcies listing or change the text on the button to be consistent.

**Comment by pmackay** [comment]
Closing as we're not going to add text directly via those links.
