### ISSUE TITLE
Gallery posting now being used - need to sort name etc

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#608]
new site

I notice that Mimosa deli has started to post images in the gallery. Currently it is a test gallery and therefore still has the latin text and no proper name.

Are we ready for images to be posted? If so, can we edit the info there.

**Comment by pmackay** [comment]
Should be fine to post new images. There is an issue related to editing
migrated ones I need to fix.

Can you consider what gallery(s) you want to create to "store" people's
pictures? Where would Mimosa put their pictures? Creating galleries is an
editor task.

**Comment by GilesGibson** [comment]
Not sure of the relationships between galleries, groups, traders and the site in general.

@pmackay Would it be possible for a brief explanatory paragraph to be done for the admin manual?

**Comment by pmackay** [comment]
Do you mean how galleries work? There isnt much relationship to traders...

**Comment by GilesGibson** [comment]
Ok, that sorts that bit then.

**Comment by djwesto** [comment]
@GilesGibson Please could you start a list (either here or on a new Google Drive doc) of galleries you'd like to start on the site? Also, where are your images currently stored?

**Comment by GilesGibson** [comment]
@djwesto No idea where the library of images are stored. There are all the ones uploaded to the site for general addition to news items etc plus the various galleries that people created. A question for @pmackay?

**Comment by pmackay** [comment]
@djwesto - what do you mean by images currently stored? Do you mean on the
site or outside of that?

**Comment by pmackay** [comment]
@GilesGibson does this help?

https://docs.google.com/document/d/1RPXdN2rqi9OdBeBaTMWzIwVVGAFMbvnqI_m8ZLIkeWU/edit#heading=h.8aji6827fzvi
