### ISSUE TITLE
Issue update email - no understandable content

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#609]
New site
Logged on as admin.

I (Admin) received an email to do with an issue update. All the contents pretty much empty:

![image](https://cloud.githubusercontent.com/assets/6060985/6964613/d631af82-d942-11e4-82d6-b78175c4bd59.png)

**Comment by GilesGibson** [comment]
Just had feedback from other users, they have been receiving the same emails, empty except for the period. No idea why they should receive anything. Will escalate this to a bug as it is affecting other users.

**Comment by pmackay** [comment]
Did you get any other emails from issues being updated? Did you see the Comment notify checkboxes related to getting email replies?

**Comment by GilesGibson** [comment]
I had a few of the single dot emails yesterday afternoon. If the email was in response to a new comment being added then gerat, that can be edited in profiles. However, be good to mention that in the email that arrives, a dot isn't the ideal!

**Comment by pmackay** [comment]
Please test if these are improved now.

**Comment by GilesGibson** [comment]
@pmackay Can we get access to edit the text that is sent with each type of email? Bo good to have some personalisation.

**Comment by GilesGibson** [comment]
@pmackay I just answered an issue request to create a new business listing. I requested a copy of the email to be sent to me as I answered the issue. I got one email with the subject line "Herne Hill Issue update:" contents was only "see." 
Another then arrived with the subject line "Herne Hill: Issue update: Paul Lupton Garden Services" and had the content of "See http://www.hernehill.org.uk/issues/paul-lupton-garden-services."

Looks like there is still a notification email coming out that has no reference to anything on the site. The follow up email has the link. It would be really helpful if we could include the contents of the "reply" in the link to save having to go on to the site and read something that is not relevant.

**Comment by djwesto** [comment]
So, @pmackay is there already a structure in place for how these emails _should_ be formatted which just isn't getting injected into the email body for some reason? Or is there actually a piece of work to be done here to actually configure all site emails correctly with tokenised content to add personalisation in?

If so, would it help for us to sit down and work them all out, write each email and then set them up?

Or could we get @GilesGibson to write all the emails and then we just set up the system?

**Comment by GilesGibson** [comment]
@djwesto the roles and permissions document could have a column with the text for each email in it for each scenario.

**Comment by GilesGibson** [comment]
still getting the see. email when I reply to an issue request. I assume if we are to drop issue then we don't need to chase on this problem?

**Comment by pmackay** [comment]
I would certainly prefer not to chase this problem. Depends how urgent it
is to fix.

**Comment by GilesGibson** [comment]
Not urgent.
