### ISSUE TITLE
event not showing up in What's On

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#615]
new site
logged on as admin

http://www.hernehill.org.uk/events/meet-talk-fun-palace-2015

A user created an event - the fun palace meeting. I moderated it and published it (this morning), even tweeted it. I can find it via search of the text "fun palace" but cannot see it in What's On - April 13th. User is a bit mystified as to what is happening.

You can see it if you access via the left hand calendar on the general What's up screen (selecting April 13th) cannot see it if you go in via the top menu of "week, month" etc.

**Comment by pmackay** [comment]
I think this was solved right?
