### ISSUE TITLE
spammers joining the site

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#617]
new site

logged on as admin

![image](https://cloud.githubusercontent.com/assets/6060985/6985676/c6df66e6-da2d-11e4-8be4-33b9c9d8a57f.png)

Over the last few days we have had a series of new users sign up. All with similar style user names. 

![image](https://cloud.githubusercontent.com/assets/6060985/6985716/4fdbd344-da2e-11e4-8cc6-3a16e1bcf799.png)

Looks like there is a spam robot out there somewhere getting access to the site. I haven't seen any content being posted as yet but maybe that comes later. I normally track this sort of thing and delete the user and all their content as soon as they post something.

On of the frustrating issues is that every login then gets sent to mailchimp and it adds to our total for their billing purposes. We are therefore paying to have spammers on the site and to be added to Mailchimp. 

Not sure what is possible to do about it until they blow their cover and post something. I hope they are not adding/editing anything elsewhere that we cannot see.

**Comment by pmackay** [comment]
Have you ever used Mollom? If not, do you want to try?

**Comment by GilesGibson** [comment]
I normally just take paracetamol, is Mollom good? Does it get rid of the pain from spammers? I think you mentioned it before, remind me what it does? I think we may have had it on the old site.

**Comment by pmackay** [comment]
https://www.mollom.com/how-mollom-works

Just uses central data to help filtering. Might apply a bit more to when
people post spam comments (not a problem you have). But could be useful
anyway.

**Comment by pmackay** [comment]
Actually just checked and Honeypot was not enabled for registration form.
So lets see if that helps first (it prevents auto spammers).

**Comment by GilesGibson** [comment]
OK, thanks. I think I may delete those logins, they look suspicious.
