### ISSUE TITLE
What twitter account is used when the twitter icon clicked

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#625]
new site
logged on as admin.

I am perplexed as to how the system/life etc knows what Twitter account to use when the Tweet icon is selected. has been one account for a while (HerneHillforum one), now it has decided to use a different account that I have.

I assume it is due to something somewhere but would love to know.

**Comment by pmackay** [comment]
Which tweet button do you mean? If you mean the ones for sharing on every
article, etc, they use whatever account you are logged in with on the same
browser. So anyone can use them.

**Comment by GilesGibson** [comment]
Thats what I thought. I run 4 accounts via Hootsuite. No idea how it chooses what account to post on. To start with it was HH Forum, last time it wanted my @ggatlarge account. Obviously there is a flag somewhere within Chrome/Apple OS that sets the current default twitter account. Just stumped as to where it is or how I change it.

**Comment by pmackay** [comment]
Surely there is one account that you are logged into via Twitter? If you open Twitter, not Hootsuite, what account is logged in?

**Comment by GilesGibson** [comment]
I never (or rarely) run Twitter, just Hootsuite within the browser. Somewhere there must be a cookie or similar that is being used to determine the active account.

**Comment by pmackay** [comment]
OK. I dont know then, not sure what Hootsuite does.

**Comment by GilesGibson** [comment]
all very strange. Will add it to the backlog as I think we need to know what the module on Drupal looks for, be useful in the future.

**Comment by pmackay** [comment]
Well its only embedding the standard share widgets that social networks
provide. What account is used if you tweet on a totally different website?

**Comment by GilesGibson** [comment]
Hmm, not sure I have done that apart from using the mobile, and that fires up twitter.

**Comment by pmackay** [comment]
So how are you tweeting?

**Comment by GilesGibson** [comment]
I was originally only having Hootsuite running in Chrome. I have now loaded up twitter as well in a tab so that it can send tweets out. strange.

**Comment by pmackay** [comment]
No I mean how are you triggering them from HH site? Which was the root of
this issue right?

**Comment by GilesGibson** [comment]
As detailed. Load twitter page in Chrome, select the account I want and leave it. HH site in another tab then seems to tweet to the correct account. Will experiment more.
