### ISSUE TITLE
Error when clicking on event

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#626]
new aite
logged in as admin.

When I clicked on the event: "French playground" in the left hand column I got this:

![image](https://cloud.githubusercontent.com/assets/6060985/6996977/f32b019c-db9f-11e4-8c7e-9ac250d81524.png)

**Comment by pmackay** [comment]
I've discovered a bug in the comments migration that means any node with comments will probably fail like this. There are 478 comments on nodes (some nodes might have multiple comments). I think I can still try a rollback and re-import of comments but will need to test and take site offline while I re-import. Might aim to do tomorrow morning, unless there is a time that would be preferable?

**Comment by GilesGibson** [comment]
That time would be fine.

**Comment by pmackay** [comment]
Fixed now. Please check and report any similar issues. Content should now have visible comments where they were added before.
