### ISSUE TITLE
Web site time is on GMT

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#633]
new site

Just noticing that the web site time seems to be on GMT. Issues, items posted etc displayed in Content is all one hour behind. If it is easy to fix and to get the web site to update automatically with BST etc then great.

**Comment by pmackay** [comment]
Could you please double check this again?

**Comment by pmackay** [comment]
FYI, I set the default timezone to London (was UST before) and set default country. Be good to know if that solves it.

**Comment by GilesGibson** [comment]
OK, will monitor. It was just that before I would post a comment and it reported that I had done it an hour ago...

**Comment by pmackay** [comment]
Can you test again to verify?

**Comment by GilesGibson** [comment]
looks OK now. Thanks.

**Comment by GilesGibson** [comment]
@pmackay Just had this support query through  from a user:

Just trying to finish off what Tim started - all the times he has put in for things to start are one hour ahead - even when I go in and change them back an hour to the correct time, they still come back as an hour off. Am I doing something wrong or is the website not on GMT?
Thanks!

They were trying to add an event for the HHFFF.

**Comment by pmackay** [comment]
Going to close this as I think it was due to the timezone not being set before, and then we hit the 1 hour change. Note this from Drupal docs about entering dates if the date is configured to use the site's time zone (which event dates are):

> Site's time zone - When entering data into the field, the data entered is assumed to be in the site's time zone. When the data is saved to the database, it is converted to UTC. When retrieved from the database, the data is converted to the Site's time zone for anonymous users or the User's time zone for logged in users when User-configurable time zones is enabled.
