### ISSUE TITLE
Image not displaying in event

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#644]
new site
logged in as admin

http://www.hernehill.org.uk/events/london-consorts-winds-ancient-modern-consort-otc-weds-april-15th

A new event has been posted by Alex (an admin person). The image for the event is not showing:

![image](https://cloud.githubusercontent.com/assets/6060985/7154561/252e6600-e34f-11e4-9cf7-19dde31830ac.png)

However, if you look at the draft it appears fine.

**Comment by pmackay** [comment]
I can see 2 images on there.

**Comment by djwesto** [comment]
Is this another caching issue?

**Comment by GilesGibson** [comment]
dont think so. Visible when you edit the event. It shows the icon for an image but didn't show the image. Could be a browser issue.

**Comment by pmackay** [comment]
I can see both images.
