### ISSUE TITLE
Forum spamming

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#649]
new site.

We have suffered on two occasions over the last two days with spammers doing mass entries on the site. Loads of forum postings for the usual range of chemicals. I have deleted the logins and their content each time.

Looks like there is robot software out there that can work with the Drupal forum software and generate auto-spam posts. 

is there anything we can do to reduce this whilst we still use the Drupal module?

Will harmony be any better?

on the plus side, glad they managed to find us, Google wouldn't have managed it.

**Comment by pmackay** [comment]
Are these "users" that just signed up recently?

**Comment by GilesGibson** [comment]
yes, they create their logins, wait a few hours then go for it.

**Comment by pmackay** [comment]
do you want to try Mollom as well?

**Comment by pmackay** [comment]
next time could i review the content before its all deleted?

**Comment by GilesGibson** [comment]
I dont want to add extra right now to your workload. If it doesn't get any worse then I can do the manual fire and forget routine. As long as we can make sure Harmony is better then fine. Lets wait until Harmony breezes in.

**Comment by GilesGibson** [comment]
why, you needing that sort of medication?

**Comment by pmackay** [comment]
Harmony wont make any difference to whether spammers post stuff or not.

**Comment by GilesGibson** [comment]
I realise that it won't stop the occasional one off. What we had was 20 or so all posted within minutes of each other. I suppose they have written the scripts for the common forum software systems. Maybe the script for harmony hasn't been written yet....

**Comment by GilesGibson** [comment]
@pmackay just got spammed again

http://www.hernehill.org.uk/revatio-fast-kansas

**Comment by pmackay** [comment]
Have tweaked settings a bit. Delete if you like...

**Comment by GilesGibson** [comment]
I have deleted them, plus a load of ones that were in the "alert" option. Getting a bit of a problem is it continues.

**Comment by pmackay** [comment]
Keep us updated. Would like to see if honeypot changes improve it.

**Comment by GilesGibson** [comment]
just been spammed again. Have deleted them.

**Comment by pmackay** [comment]
How often did this happen on old site?

**Comment by GilesGibson** [comment]
once every two months. Then only a single post, never the huge numbers that we have at the moment.

**Comment by pmackay** [comment]
Wonder if its something about a new domain appearing...

**Comment by GilesGibson** [comment]
I have noticed that there are still a few users with @drupaler accounts. I think the ones I deleted had those accounts suffixes. Bet they trigger the robot shortly to start spamming. Interesting they managed to get in to the alerts...

**Comment by GilesGibson** [comment]
yup, they have just hit the site @drupaler seems to be a source. Deleted two of them who had spammed. Checked in the people list and saw three more accounts from drupaler, they are now ex-accounts.

**Comment by GilesGibson** [comment]
two more @drupaler logins deleted. More spam this morning.

**Comment by pmackay** [comment]
Do you want to try anything different with this?

**Comment by GilesGibson** [comment]
They are spamming the Alert option. 

They can obviously create logins automatically, having to delete a couple each day at the moment. 

Not sure of harmony will defeat them as they may not have written the scripts for that forum module.

**Comment by pmackay** [comment]
Dont think Harmony will make a difference. Key thing is to stop accounts
being created.

**Comment by GilesGibson** [comment]
OK, can we block any accounts ending in  @ drupaler?

**Comment by pmackay** [comment]
The approach I'd take with that is to setup Mollom, which analyses spam
data across the web.

**Comment by GilesGibson** [comment]
Is there a way of knowing what it has blocked in case good stuff goes the way of spam? Would it stop the alerts being stuffed with items?

**Comment by pmackay** [comment]
What what has blocked?

**Comment by GilesGibson** [comment]
Mollom would do what then? just report on suspicious content? I thought it could be the guide to content that should be blocked. probably misunderstood it.

**Comment by pmackay** [comment]
Yes it does block suspicious content, pretty sure there would be a list of
what it had blocked somewhere that could be viewed.

**Comment by GilesGibson** [comment]
and unblock it?

**Comment by pmackay** [comment]
Not sure, we'd have to test it out.

**Comment by GilesGibson** [comment]
On the live site?

**Comment by pmackay** [comment]
Could try on dev first if needed.

**Comment by GilesGibson** [comment]
no spam there though. We could contact the idiots and ask them to test spam dev? :-)

**Comment by pmackay** [comment]
Well, try on live then :)

**Comment by GilesGibson** [comment]
as long as we can find any blocked content and release it. Otherwise people will get fed up that their posts have disappeared.

**Comment by pmackay** [comment]
Surely the important thing is stopping new accounts?

**Comment by GilesGibson** [comment]
does Mollom stop new accounts? If so on what criteria?

**Comment by pmackay** [comment]
https://mollom.com/how-mollom-works

So for user registration it would introduce a Captcha but could compare
account info with a central database.

**Comment by GilesGibson** [comment]
Ah, we used to have captcha and had a few issues, had to tone it down a bit as some people stumbled on it. Be good to have it back at a medium to low level. happy to have it update/check a central database.

**Comment by pmackay** [comment]
So you want to try it out?

**Comment by GilesGibson** [comment]
yup, I deleted two accounts an hour ago. A new one has already appeared.

**Comment by pmackay** [comment]
Have enabled mollom with a Captcha on the login form. Please see if it has a difference.

**Comment by GilesGibson** [comment]
Loads of spam today, on Alerts. The user may have created their login before captcha was instigated though.

**Comment by GilesGibson** [comment]
All quiet on the Western front

**Comment by GilesGibson** [comment]
spoke too soon. Two more users from @drupaler - spammed the site, abuse reports, forum etc.

**Comment by pmackay** [comment]
Is spamming at a manageable level now? OK to close?

**Comment by GilesGibson** [comment]
yup
