### ISSUE TITLE
User names - can they change their login name?

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#650]
New site
logged in as admin.

A query from a user - can they change their login name? 

In theory within "my account" they could edit their name, I think. However, would that affect their content that they had created? Would it change the authors name, going back in time? What about the service listing that they can edit?

What are the risks?

**Comment by pmackay** [comment]
I think they should be able to edit their usernames. All content is
referenced by user ID, which they cannot change.

**Comment by GilesGibson** [comment]
ta

**Comment by GilesGibson** [comment]
a standard user cannot see the field. @pmackay can this be changed

**Comment by pmackay** [comment]
Ooops, true. Have fixed permission now.
