### ISSUE TITLE
user unable to change password

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#657]
live site.

User "taniath" - is trying to reset their password. Asks for a new pasword activation to be sent, never gets to them. I reset their password for them, they can login but when they try and reset it, again, no email received. They have checked spam etc and nothing there.

tempesthay@hotmail.com is their email address.

@pmackay could this be a hotmail issue?

**Comment by GilesGibson** [comment]
Just ha another issue raised on the site, another user cannot create a login due to the email never reaching them.

amandadacosta86@yahoo.com 

@pmackay Looks like something may be broken.

**Comment by pmackay** [comment]
Two replacement login emails were sent to tempesthay@ on 19 May around
10.55pm, sent successfully. Any chance its gone to spam?

There are no records of any emails being sent to amandadacosta86@yahoo.com.
Can they try another email?

**Comment by GilesGibson** [comment]
Re: tempesthay@ email. As mentioned in first post, I asked them to check their spam, nothing there. I tried again after resetting their password manually, looks like the email may have gone but got stuck somewhere. 

Strange we have had two in the space of 24 hours.

I can ask amandadacosta@ to try to set up a new login with a new email address.

**Comment by pmackay** [comment]
Have these been resolved? Can we close?

**Comment by GilesGibson** [comment]
not to my knowledge. They just tend to get fed up and stop using the site

**Comment by pmackay** [comment]
Have you had any more of these recently?

**Comment by pmackay** [comment]
Closing but happy to review if more info can be determined.
