### ISSUE TITLE
Tags in service listing

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#660]
New site

A query from a service lister. They have created some tags. How do they get their tags listed on the main services page where you can filter by tag?

@pmackay Will the site eventually update that list automatically next time a script runs or is it a manual process?

**Comment by pmackay** [comment]
Do the tags appear once you filter by a category?

**Comment by GilesGibson** [comment]
yes.

**Comment by pmackay** [comment]
Great, is that ok then?

**Comment by GilesGibson** [comment]
how would the tag get to the main services listing page where the other tags are?

**Comment by pmackay** [comment]
I meant do they appear on the listing page with other tags, when a category
is filtered on?

Can you give a link, and what tags you want to appear where?

**Comment by GilesGibson** [comment]
no, hence the question. The service user is Brockwell Park massage. They had some tags that didn't appear on the main services page. I explained that it would be good to use the same tags as already there but they also had an extra one. I had thought that the tags would slowly accumulate/update on the front page. Is this the case or do we have to manually add them?

**Comment by pmackay** [comment]
I think the problem here is that some of those tags only have that one entry. There is probably a setting to say only show a tag once it has been used 2/3 or more times. Which seems logical to me and a way to prevent a very large list of tags used only once. "deep tissue massage" appears 7 times...
