### ISSUE TITLE
Contact form to have Captcha

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#665]
New site.

Could we have some sort of antis-spam filter applied to the contact form. Been getting loads of junk messages via the contact form and the Issue form. I know that we will probably drop the issue form but I think we are getting spam via the contact form too. A simple captcha would help reduce the background noise.

**Comment by pmackay** [comment]
Have enabled Mollom scanning for both those forms. Please report back on whether its effective.

**Comment by GilesGibson** [comment]
Be good to have it on the VAC site as well, getting rubbish from them too.

**Comment by pmackay** [comment]
Can you comment on whether its helped on the HH site?

**Comment by GilesGibson** [comment]
HH better. Will keep checking. Thanks. I think it was just a robot that learnt how to send messages through.

**Comment by pmackay** [comment]
Have added https://github.com/folklabs/openlocal/issues/23 for other sites.
