### ISSUE TITLE
Web site error - events page

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#677]
Just clicked on Whats On and got this:

![image](https://cloud.githubusercontent.com/assets/6060985/10738814/11f3685a-7c11-11e5-8c8f-6f8754c31dfd.png)

**Comment by pmackay** [comment]
maybe just give this a bit of time and check again. Looks like a systems thing from Pantheon.

-- 
Paul Mackay

On 26 October 2015 at 18:41:04, GilesGibson (notifications@github.com) wrote:

Assigned #677 to @pmackay.

**Comment by pmackay** [comment]
@GilesGibson ever seen this again?

**Comment by GilesGibson** [comment]
nope
