### ISSUE TITLE
Item not being published

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#679]
News item appears in content. Change to publish, not appearing on site. Been a couple of hours now. Endless refresh to no avail.

http://www.hernehill.org.uk/events/crisis-midwinter-swim-series

**Comment by pmackay** [comment]
I can see it visible on http://www.hernehill.org.uk/events/day/2015-12-12. Where are you expecting it to show that it isnt?

**Comment by GilesGibson** [comment]
sorry, I was getting confused with other stuff that should be going in news. Broken broadband this end and too much happening.  Apologies. Ignore this issue. As you were....

**Comment by pmackay** [comment]
OK no probs.
