### ISSUE TITLE
Password issues

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#681]
Had a support call regarding resetting passwords:

"Hi Giles

Thanks for your prompt reply!

The link does work - the problem is that you need your current password to set a new one. As all you get is a direct link and no temporary password, you are left unable to reset your password.

What I need is a temporary password along with the link so that I can reset my password on my account page. Is that possible?

Many thanks
Elisabeth

Sent from my iPod

On 23 Nov 2015, at 09:44, Giles Gibson giles@originaltg.com wrote:
Elisabeth
Really sorry to hear your are having problems with resetting your
password.
In theory, the reset link should work to let you back in. You can then go
to your profile and change your password there. If it doesn¹t let you then
drop me a line and I will reset it this end.
Thanks
Giles
On 22/11/2015, 20:47, "Herne Hill"

glowstick (http://www.hernehill.org.uk/users/glowstick) sent a message
using
the contact form at http://www.hernehill.org.uk/contact.
hello there
HAving forgotten my password, I requested a new one. I clicked on the
login
link I was emailed but while I was able to login and access my account, I
can't reset my password - as I have not been provided with a "current one"
required to reset it. All I got was a link.
Can you help?
Many thanks.
Elisabeth
Report as inappropriate:
http://www.hernehill.org.uk/mollom/report/mollom_content/1511227c72e1f3e33
d"

Not sure what is going on here - looks like they are in a loop as the site will not let them reset their password permanently. Any ideas?

**Comment by pmackay** [comment]
The login link it sends should allow a 1-time login to allow the user to save a new password. It doesnt require the old password. I just tried and it seems to work fine.

**Comment by GilesGibson** [comment]
I have got back to them. We may need to update the text that we include with the password reset email and link.

**Comment by pmackay** [comment]
Can you confirm if they were able to make it work?

**Comment by GilesGibson** [comment]
I am waiting to hear back.

**Comment by pmackay** [comment]
Closing as no further updates.
