### ISSUE TITLE
Web site not responding

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#685]
Users have complained that the web site is not responding. 9:50 p.m. Wednesday 3rd Feb. Just spinning wheel.

**Comment by pmackay** [comment]
Just loaded it, seems ok to me. Could have been just a temp blip?

**Comment by GilesGibson** [comment]
was it a hosting issue? Just got an error page eventually (not our error page though).

**Comment by pmackay** [comment]
I dont know but probably...
