### ISSUE TITLE
Determine redirection for hernehillforum.org.uk

### ISSUE THREAD

**Issue by pmackay** [folklabs/hernehill.org.uk#70]
* [ ] Consider embedded links in existing content
* [ ] Do we setup redirect links for existing links?
* [ ] How to manage redirect from old domain?

**Comment by pmackay** [comment]
@GilesGibson could the maintenance mode of current HH site just have a link to the new site once new site is live?

**Comment by GilesGibson** [comment]
If we cannot redirect people with a nice message then fine. Need to do a good slash screen asking people to go to the new site, update their shortcuts and so forth. Not sure how we will broach the issue with those loyal followers who got the old URL tattooed to their forehead.

**Comment by pmackay** [comment]
Closing this as we have message. Can change to redirect later if needed.
