### ISSUE TITLE
Image appearing rotated in news item

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/hernehill.org.uk#702]
The news story: http://www.hernehill.org.uk/node/18071/edit has an image included. It displays correctly in editing mode but when published it gets rotated 90 degrees. Cannot figure out how to fix this. Really frustrating, such a simple thing and Drupal just plays silly buggers. Makes the site look a bit naff.

**Comment by pmackay** [comment]
Can you rotate the image initially using some other software first?

**Comment by GilesGibson** [comment]
How do I get hold of the image file? It was uploaded by another user.

**Comment by pmackay** [comment]
Fixed. I went to edit view, downloaded the image via the link, rotated it Left and then Right in Preview, saved it and re-uploaded.
