### ISSUE TITLE
Styling and alignment needed for News Article page – Author details block

### ISSUE THREAD

**Issue by djwesto** [folklabs/hernehill.org.uk#95]
The styling currently looks like this:

![screen shot 2014-01-22 at 14 34 30](https://f.cloud.github.com/assets/702685/1974712/771f7eaa-8373-11e3-8347-36d65e7d3c41.png)

But was supposed to look like this:

![screen shot 2014-01-22 at 14 43 33](https://f.cloud.github.com/assets/702685/1974729/aba363f8-8373-11e3-97c4-cd62a5e87fe4.png)

**Comment by pmackay** [comment]
These page bits now moved to sidebar and improved anyway.
